// Maps a raw `sets.theme` value (Rebrickable's full theme/subtheme taxonomy,
// ~370 distinct strings) to this site's curated `/themes/<slug>` taxonomy
// (src/lib/brand.ts THEMES, ~28 entries) -- or explicitly to `null` when a
// raw theme has been reviewed and deliberately gets no theme link at all
// (non-buildable merch, education/robotics, collectible minifig series,
// or a low/zero-commercial-relevance vintage cluster).
//
// Built from the full-catalog theme audit in
// docs/audits/theme-mapping-proposal.csv (BOI Fix Brief, 2026-08-28) --
// fixes HIGH-Theme404 (src/app/sets/[slug]/page.tsx's breadcrumb used to
// build `/themes/${slugify(set.theme)}` directly from the raw value with
// no validation, 404ing for any set whose theme wasn't one of the 25
// original curated names).
//
// A raw theme NOT present as a key here (the long, still-`NEEDS_DECISION`
// tail in the CSV, plus Pokémon pending its own review) falls through to
// resolveThemeSlug()'s slugify-and-validate fallback below -- safe by
// construction: it never links anywhere that isn't a real curated slug, so
// it can't 404, it just renders as plain unlinked text until reviewed.
export const RAW_THEME_MAP: Record<string, string | null> = {
  "Activity Books": null,
  "Activity Books with LEGO Parts": null,
  "Advent": "seasonal",
  "Alien Conquest": null,
  "Aquanauts": null,
  "Aquaraiders I": null,
  "Aquaraiders II": null,
  "Aquasharks": null,
  "Aquazone": null,
  "Atlantis": null,
  "Audio and Visual Media": null,
  "Avengers": "marvel",
  "Bag and Luggage Tags": null,
  "Bags, Totes, & Luggage": null,
  "Basic": null,
  "Basic Set": null,
  "Batman": "dc",
  "Bionicle": "bionicle",
  "Black Falcons": null,
  "Black Knights": null,
  "Blacktron I": null,
  "Blacktron II": null,
  "Books": null,
  "Botanicals": "botanical",
  "Brick Sketches": null,
  "Bricktober": null,
  "Building": null,
  "Building Set with People": null,
  "Bulk Bricks": null,
  "Captain America": "marvel",
  "Cars": "disney",
  "Castle": null,
  "Chinese (Lunar) New Year": "seasonal",
  "Chinese Traditional Festivals": "seasonal",
  "City Center": "city",
  "Classic Basic": "classic",
  "Classic Space": "classic",
  "Classic Town": "classic",
  "Clocks and Watches": null,
  "Clothing & Footwear": null,
  "Coast Guard": "city",
  "Collectible Minifigures": null,
  "Control Lab": null,
  "Creator 3-in-1": "creator",
  "Creator Expert": "creator",
  "DC Comics": "dc",
  "DC Comics Super Heroes": "dc",
  "DC Super Hero Girls": "dc",
  "DC Super Heroes": "dc",
  "DFB Minifigures": null,
  "Dark Forest": null,
  "Database Sets": null,
  "Designer Sets": null,
  "Discovery": null,
  "Disney 100": "disney",
  "Disney Princess": "disney",
  "Disney Series 1": "disney",
  "Disney Series 2": "disney",
  "Doc McStuffins": "disney",
  "Dolls": null,
  "Dragon Knights": null,
  "Duplo and Explore": "duplo",
  "EV3": null,
  "Early Creator": "creator",
  "Easter": "seasonal",
  "Editions": null,
  "Educational and Dacta": null,
  "Exploriens": null,
  "FIRST LEGO League": null,
  "Fantasy Era": null,
  "Farm": "city",
  "Fire": "city",
  "Forestmen": null,
  "Fright Knights": null,
  "Frozen": "disney",
  "Futuron": null,
  "Galaxy Squad": null,
  "Games": null,
  "Gear": null,
  "Guardians of the Galaxy": "marvel",
  "Halloween": "seasonal",
  "Hobby Sets": null,
  "Hospital": "city",
  "Houseware": null,
  "Hydronauts": null,
  "Ice Planet 2002": null,
  "Ideas Books": "ideas",
  "Incredibles 2": "disney",
  "Insectoids": null,
  "Inventor": null,
  "Iron Man": "marvel",
  "Iron Man and His Awesome Friends": "marvel",
  "Jumbo Bricks": null,
  "Jurassic Park III": "jurassic-world",
  "Jurassic World: Fallen Kingdom": "jurassic-world",
  "Justice League": "dc",
  "Key Chain": null,
  "Kingdoms": null,
  "Knights Kingdom I": null,
  "Knights Kingdom II": null,
  "LEGO Brand Store": null,
  "LEGO Exclusive": null,
  "LEGO Ideas and CUUSOO": "ideas",
  "LEGO Originals": null,
  "Launch Command": null,
  "Learning": null,
  "Learning at Home": null,
  "Legends of Chima": "legends-of-chima",
  "Legoville": "city",
  "Life On Mars": null,
  "Lightyear": "disney",
  "Lion Knights": null,
  "M:Tron": null,
  "Magnets": null,
  "Make & Create": null,
  "Mars Exploration": null,
  "Mars Mission": null,
  "Marvel Series 1": "marvel",
  "Marvel Series 2": "marvel",
  "Marvel Super Heroes": "marvel",
  "Mickey & Friends": "disney",
  "Mickey Mouse": "disney",
  "Miles From Tomorrowland": "disney",
  "Mindstorms": null,
  "Mission Deep Freeze": null,
  "Mission Deep Sea": null,
  "Monthly Mini Model Build": null,
  "Mosaic": null,
  "My Town": "city",
  "NXT": null,
  "Nexo Knights": "nexo-knights",
  "Ninja": "ninjago",
  "Non-fiction Books": null,
  "Other": null,
  "Pick A Model": null,
  "Planes": "disney",
  "Playsets": null,
  "Plush Toys": null,
  "Posters and Art Prints": null,
  "Power Functions": null,
  "Power Miners": null,
  "Powered Up": null,
  "Princess Castle": null,
  "Promotional": null,
  "RCX": null,
  "Rattles": null,
  "RoboRiders": null,
  "Rock Raiders": null,
  "Role Play Toys and Costumes": null,
  "Royal Knights": null,
  "SPIKE": null,
  "Sculptures": null,
  "Series 1 Minifigures": null,
  "Series 10 Minifigures": null,
  "Series 11 Minifigures": null,
  "Series 12 Minifigures": null,
  "Series 13 Minifigures": null,
  "Series 14 Minifigures": null,
  "Series 15 Minifigures": null,
  "Series 16 Minifigures": null,
  "Series 17 Minifigures": null,
  "Series 18 Minifigures": null,
  "Series 19 Minifigures": null,
  "Series 2 Minifigures": null,
  "Series 20 Minifigures": null,
  "Series 21 Minifigures": null,
  "Series 22 Minifigures": null,
  "Series 23 Minifigures": null,
  "Series 24 Minifigures": null,
  "Series 25 Minifigures": null,
  "Series 26 Minifigures": null,
  "Series 27 Minifigures": null,
  "Series 28 Minifigures": null,
  "Series 29 Minifigures": null,
  "Series 3 Minifigures": null,
  "Series 4 Minifigures": null,
  "Series 5 Minifigures": null,
  "Series 6 Minifigures": null,
  "Series 7 Minifigures": null,
  "Series 9 Minifigures": null,
  "Serious Play": null,
  "Service Packs": null,
  "Sofia the First": "disney",
  "Soft Bricks": null,
  "Space": null,
  "Space Police I": null,
  "Space Police II": null,
  "Space Police III": null,
  "Space Port": null,
  "Spider-Man": "marvel",
  "Spider-Man - Across the Spider-Verse": "marvel",
  "Spidey and His Amazing Friends": "marvel",
  "Spyrius": null,
  "Stationery and Office Supplies": null,
  "Stingrays": null,
  "Storage": null,
  "Story Books": null,
  "Super Heroes DC": "dc",
  "Super Heroes Marvel": "marvel",
  "Superman": "dc",
  "Supplemental": null,
  "Tabletop Games and Puzzles": null,
  "Thanksgiving": "seasonal",
  "The Infinity Saga": "marvel",
  "The LEGO Batman Movie": "dc",
  "The LEGO Batman Movie Series 1": "dc",
  "The LEGO Batman Movie Series 2": "dc",
  "The LEGO Movie": "ninjago",
  "The LEGO Movie II": "ninjago",
  "The LEGO Ninjago Movie": "ninjago",
  "Time Cruisers": null,
  "Toolo": null,
  "Town": "city",
  "Town Jr.": "city",
  "Toy Story": "disney",
  "Traffic": "city",
  "Train": "city",
  "Trains": "city",
  "UCS": "icons",
  "UFO": null,
  "Ultimate Collector Series": "icons",
  "Unitron": null,
  "Unknown": null,
  "VIP Add-On Packs": null,
  "Valentine": "seasonal",
  "Value Packs": null,
  "Vehicle": null,
  "Video Games and Accessories": null,
  "Villains": "dc",
  "WeDo": null,
  "Western": null,
  "Winnie the Pooh": "disney",
  "World City": "city",
  "X-Men": "marvel",
  "Znap": null,
};

import { THEMES } from './brand';
import { slugify } from './utils';

const CURATED_SLUGS = new Set<string>(THEMES.map((t) => t.slug));

// Resolves a raw `sets.theme` value to the curated `/themes/<slug>` this
// site should link to, or `null` if it shouldn't link anywhere.
//
// Order: (1) explicit RAW_THEME_MAP entry, including explicit `null` for a
// reviewed exclusion -- checked first so a deliberate exclusion always wins
// even if the raw string would otherwise slugify to a real curated slug
// (not currently possible given the two lists don't overlap, but this
// ordering is what makes that a non-issue rather than a footgun); (2) a
// direct slugify match against a real curated slug (covers the ~20
// DIRECT_MATCH themes, e.g. "Star Wars" -> "star-wars", with no need to
// enumerate them here too); (3) no link.
export function resolveThemeSlug(rawTheme: string | null | undefined): string | null {
  if (!rawTheme) return null;
  if (Object.prototype.hasOwnProperty.call(RAW_THEME_MAP, rawTheme)) {
    return RAW_THEME_MAP[rawTheme];
  }
  const slug = slugify(rawTheme);
  return CURATED_SLUGS.has(slug) ? slug : null;
}

// Reverse lookup for a curated theme page's set listing: every raw theme
// value that has been explicitly mapped to this curated slug (used to
// supplement /themes/[theme]/page.tsx's existing ilike('%name%') match,
// which alone would miss e.g. "Batman" on the DC page -- the substring
// "DC" never appears in "Batman").
export function rawThemesFor(curatedSlug: string): string[] {
  return Object.entries(RAW_THEME_MAP)
    .filter(([, v]) => v === curatedSlug)
    .map(([k]) => k);
}
