-- boi:issue 246
-- boi:backup-tables public.reviews
-- boi:expect-before select count(*) from public.reviews where (slug, md5(content)) in (values ('lego-the-endurance-10335-worth-22899','ab6edc2001c07b9d8853c8ba2d6f635c'), ('lego-77254-ferrari-sf90-xx-stradale-worth-2999','4b18ef8491686bb4b078c39024f909cf'), ('lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999','b8421a405a3fa36280938cbf22f82ef6'), ('lego-stranger-things-the-creel-house-11370-worth-27999','4dd50572f2467b6599d6fe1384653827'), ('lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag','c27812f49a4130c419b1a9c9253a5f4c'), ('lego-tower-bridge-21067-worth-10300','03bc82969d673497c01b29ff8f835f79'), ('lego-10326-natural-history-museum-review','d24eb02f04e1ed34ca87a938454e05cd'), ('lego-40896-the-x-files-scullys-lab-gwp-is-this-a-must-have','c6f728d65efe1cd5b7c217d6c392dde8'), ('lego-gremlins-gizmo-and-stripe-40919-worth-3300','98026f1778d7b86a67d2eeacde4c84fe'), ('lego-city-police-train-heist-60508-19999-for-a-cat-and-mouse','36b86ca5e1929105ba5cf594a6be9739'), ('lego-avengers-tower-76269-worth-39199','558e63b15ba91a5cb4a48b2b1c0298aa'), ('lego-darth-vaders-lightsaber-40897-worth-the-import-price','daeb69a84dab600de2692129669c9f35')) and exists (select 1 from public.store_prices where set_id = '40912' and store_id = 'mybrickhouse' and in_stock and price_inr = 2499) = 12
-- boi:expect-after select count(*) from public.reviews where (slug, md5(content)) in (values ('lego-the-endurance-10335-worth-22899','1f096aad19073975d29aedfa2ebd9b4f'), ('lego-77254-ferrari-sf90-xx-stradale-worth-2999','b5903c79db670900a48c9d2a0cbbdf30'), ('lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999','894e02ac1386318992fee4a2ce8c921c'), ('lego-stranger-things-the-creel-house-11370-worth-27999','6509668c67d04642fba740ec9e99cdbc'), ('lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag','821f3728e0aed95a6ebcbe9c43b47b50'), ('lego-tower-bridge-21067-worth-10300','d480310e13e01ca1f3aba1aa43b4eb0c'), ('lego-10326-natural-history-museum-review','aa37903e937aced451f4b40987617656'), ('lego-40896-the-x-files-scullys-lab-gwp-is-this-a-must-have','06a19721d27dad2dc550d4487f9f0366'), ('lego-gremlins-gizmo-and-stripe-40919-worth-3300','e5b7ac449fb5338c0ea67ae9d525b072'), ('lego-city-police-train-heist-60508-19999-for-a-cat-and-mouse','9db4408ff396032919b596bac19fc790'), ('lego-avengers-tower-76269-worth-39199','92404195209656c7ae81627320712353'), ('lego-darth-vaders-lightsaber-40897-worth-the-import-price','18cd7574933d228e977408ac3eba64da')) = 12
-- #246 batch 1 (P5 Step 3 / P6 Step 3): 12 reviews corrected in place with dated notes (G16), generated by
-- boi-db-backups/2026-09-27-246-batch1/make_sql.py from batch1_patch.json. Each UPDATE is guarded by the md5 of the
-- backed-up text; the before-count proves no row changed since the backup, the after-count proves every row
-- now holds exactly the reviewed text.
-- lego-the-endurance-10335-worth-22899
UPDATE public.reviews SET content = $boi_t$Your wallet called. It's not happy about the LEGO The Endurance ([10335](/sets/10335-the-endurance)). This massive 3011-piece set, recreating Sir Ernest Shackleton's ill-fated ship, is finally available in India, and at ₹22,899, it’s a serious commitment. Is this a historical masterpiece worth the investment, or a display piece that’s too much of a good thing?

Let’s talk about the elephant in the room: the price. ₹22,899 is a significant chunk of change. For that, you get a model that measures a substantial 22 inches long, 15 inches tall, and 6 inches wide. It’s a big build, and the piece count reflects that. The scale here is impressive, and LEGO has packed in a lot of detail. We're talking about a double-decker rigging system, a ship’s boat, a display stand with a nameplate, and even a few minifigures to give a sense of scale. The presentation is clearly aimed at the Icons line's target audience: adult collectors who appreciate historical accuracy and impressive display models.

The build experience itself seems to be solid, as you'd expect from a set of this caliber. The sheer size and complexity suggest a satisfying, multi-stage construction. The Endurance is a legendary ship in exploration history, and LEGO has clearly put effort into capturing its essence. The sheer number of pieces implies a detailed hull, intricate deck features, and that iconic rigging. It’s the kind of build that will occupy your coffee table for a good few weekends, and that’s part of the appeal for many.

However, the question remains: is it worth ₹22,899? This is where it gets tricky. While the set is undeniably impressive and historically significant, it's also a very niche product. Not everyone is going to have the space or the inclination to display a 22-inch model of a ship from a century ago. Compared to other large display pieces, like the Eiffel Tower or the Titanic, the Endurance might appeal to a smaller segment of the market.

At ₹22,899, it’s still a considerable sum. It’s a set that demands a specific passion for maritime history and LEGO’s larger-scale models.

Priced at ₹22,899 on MyBrickHouse, confirmed in stock as of 9 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

The model's weight (4.0 kg) also suggests a substantial build with plenty of dense elements, which contributes to the overall quality perception. But again, the price point makes it a considered purchase. If you are a die-hard fan of naval history, Shackleton's expedition, or large-scale LEGO display models, then this set might just be your dream build. The detail and scale are undeniable. But for the casual LEGO fan, or someone with a tighter budget, it’s a tough call. There are many other excellent, less expensive sets available that offer a great build and display experience without demanding such a hefty outlay.

Given the price and the niche appeal, it’s hard to give a definitive BUY NOW. While it’s available, the cost pushes it into the 'wait for a sale' territory unless you’re a dedicated collector with a specific interest in this particular historical vessel. It’s a fantastic set, no doubt, but the price is a major hurdle.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: WAIT. Good set, but the price will drop.

Corrected 29 Sep 2026: removed an unconfirmed bank-offer price and references to our source article. When we published, MyBrickHouse listed this set at ₹22,899.$boi_t$, updated_at = now()
 WHERE slug = 'lego-the-endurance-10335-worth-22899' AND md5(content) = 'ab6edc2001c07b9d8853c8ba2d6f635c';

-- lego-77254-ferrari-sf90-xx-stradale-worth-2999
UPDATE public.reviews SET content = $boi_t$Your wallet is probably already sweating. LEGO announced the [77254](/sets/77254-ferrari-sf90-xx-stradale-sports-car) Ferrari SF90 XX Stradale and it's landed in India with a price that feels… aspirational. It’s a Speed Champions set, which usually means a good time, but this Prancing Horse demands a serious look before you commit. Is this hypercar replica worth the price of admission?

The box itself is standard Speed Champions fare. A Ferrari red blur on the front, a track scene on the back. Inside, you'll find five numbered bags, the chassis, instructions, and a surprisingly small sticker sheet. For a Speed Champions set, that’s a good sign. Less fiddly stickers mean less room for error and a smoother build.

The build process is where this set shines: detailed, with enjoyable and innovative techniques. This isn't just slapping bricks together; it's a proper construction. The higher-than-average piece count for a set this size certainly helps in achieving that satisfying build experience. You start with the chassis and interior, then gradually build up the exterior, with the key details like the front section and rear wing taking shape around bag four. The final bag completes the model, leaving you with a sleek, accurate replica.

The minifigure included is a Ferrari driver, complete with a red Ferrari-branded hoodie. It’s a nice touch, especially for any Formula 1 fans looking to customise their own figures. The printed grey belt detail is a smart addition, though it does limit the hoodie’s versatility slightly. She comes with a helmet and a spanner, standard but welcome accessories.

Now, the finished model. The iconic Ferrari red is present, accented with black. The unique front end of the real SF90 XX Stradale has been translated surprisingly well into LEGO form, thanks to some clever use of wedge plates and tiles at various angles. The introduction of a couple of new pieces, like tiled versions of 1x2 angled plates, really helps achieve that smooth, flowing look. The bonnet shaping is particularly praised, with upside-down black plates adding texture and tiny gaps mimicking the real car's hood scoops. It sounds like a masterclass in LEGO car design.

The side bodywork also benefits from new pieces, including a 1x1 inverted corner cheese slope and those aforementioned 1x2 angled tiles. The printed mudguards and 1x1 slope with the Ferrari logo are a delight – printed elements are always a win. And then there are the wheels. A stunning new wheel and tyre design that is described as "stunningly Ferrari-esque." The rear, while appearing simpler, packs in clever techniques for diffuser details and bodywork shaping. Even the trans-black rear window uses those new angled tiles effectively. Access to the interior is gained by detaching the windscreen, revealing a space for two minifigures, a steering wheel with a yellow centre (a nice detail!), and some stickered interior elements.

At ₹2,999, this is the price of 14 months of Spotify Premium.
MyBrickHouse and Toycra both have it for ₹2,999. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.

The Verdict? This Ferrari SF90 XX Stradale is a strong contender in the Speed Champions line. The build experience is praised for its detail and innovation, the minifigure is a nice bonus, and the finished model is a visual treat with clever part usage and new elements. The price is a bit steep for Speed Champions, but the quality of the build and the accuracy of the final design justify it. If you’re a Ferrari fan, or just appreciate a well-designed LEGO car, this is one you’ll want to add to your collection. It’s a good build, looks fantastic, and the price, while not cheap, is fair for what you get.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Priced at ₹2,999 on MyBrickHouse and Toycra, confirmed in stock as of 21 Sep 2026.
Verdict: BUY NOW.

Standard disclaimer: if you've got the money, obviously buy it — that's what the verdict says too, for once we all agree.

Corrected 29 Sep 2026: removed narration of a source review; no factual change.$boi_t$, updated_at = now()
 WHERE slug = 'lego-77254-ferrari-sf90-xx-stradale-worth-2999' AND md5(content) = '4b18ef8491686bb4b078c39024f909cf';

-- lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999
UPDATE public.reviews SET content = $boi_t$Your wallet just did a double‑take when it saw the price tag on the new Koenigsegg Spear Megacar. 4,104 pieces, a sleek carbon‑fiber silhouette, and a price that makes even a seasoned collector pause. The [42232](/sets/42232-koenigsegg-sadairs-spear-megacar) Technic Ultimate Car Concept is the latest entry in LEGO’s high‑performance line, promising a mix of speed‑inspired aesthetics and mechanical depth. Let’s break down whether the build lives up to the hype, and if the ₹49,999 price tag is a justified pit stop.

The unboxing feels like a small ceremony. The box art is a glossy shot of the megacar poised on a racetrack, with the iconic Koenigsegg logo front and centre. Inside are 4,104 pieces, many of them new Technic elements that debuted with this series. The parts list reads like a mini‑catalog of advanced gears, ball joints, and custom‑molded pieces. If you’ve ever built a Technic car before, you’ll recognize the familiar rhythm of the build—large sub‑assemblies, a handful of intricate steering mechanisms, and a final stage where the chassis comes together.

From a construction standpoint, the set shines. The new “Spear” front splitter, made from transparent dark bluish gray, adds a tactile sense of aerodynamics. The rear diffuser, built from a series of angled plates, gives the model a genuine low‑down look that would make any supercar fan nod in approval. The build includes a working gearbox, a dual‑mode powertrain, and a fully articulated steering column that actually turns the wheels. Those details translate into a satisfying hands‑on experience that rewards patience.

Design-wise, the Koenigsegg’s signature angular lines are captured well. The front nose tapers sharply, while the rear wing extends with a realistic sweep. The color palette—deep metallic black, glossy red accents, and the signature Koenigsegg orange—looks striking on a display shelf. The model’s scale sits comfortably at around 25 cm long, making it a centerpiece without overwhelming a typical living‑room shelf. The attention to surface detail, from the carbon‑fiber texture to the tiny sponsor decals, is proof of LEGO’s collaboration with the automotive brand.

Value‑for‑pieces is where the set gets a mixed review. Compared to other Technic megas in the same price bracket, the Spear Megacar offers comparable piece counts but adds the novelty of a licensed supercar, which can be a double‑edged sword. Fans of the brand will love the authenticity; collectors looking for pure Technic engineering might feel the licensing fees inflate the price unnecessarily.

The build time is substantial—expect a long build. That’s a commitment, but the payoff is a model that looks the part.

Overall, the 42232 Koenigsegg Sadair's Spear Megacar delivers on the promises of a high‑end Technic set: intricate build, realistic design, and functional play. The price, however, sits at the top end of the market, and the licensing premium pushes it into a realm where only the most dedicated fans will feel comfortable splurging. If you’re already eyeing a spot on your shelf for a supercar, you’ll likely enjoy the build, but it may be worth waiting for a discount or bundle deal before pulling the trigger.

At ₹49,999, that's 14 months of Netflix Premium.
MyBrickHouse has it for ₹49,999. Check Toycra for availability. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Priced at ₹49,999 on MyBrickHouse, confirmed in stock as of 21 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

Corrected 29 Sep 2026: piece count corrected to 4,104 (Brickset, Rebrickable); removed claims about a motor, app control and wiring (the set has no electronic parts, per Rebrickable's inventory); ₹49,999 was MyBrickHouse's listed price when we published, not an estimate.$boi_t$, updated_at = now()
 WHERE slug = 'lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999' AND md5(content) = 'b8421a405a3fa36280938cbf22f82ef6';

-- lego-stranger-things-the-creel-house-11370-worth-27999
UPDATE public.reviews SET content = $boi_t$Your wallet just screamed. Ten years of Stranger Things, and now this. The Creel House, straight out of the final season, lands in brick form and it’s… a lot. The original Upside Down set ([75810](/sets/75810-the-upside-down)) was a beloved piece, but Vecna’s origin story demands a whole new level of LEGO tribute. This 2,593-piece monster is built to impress, complete with an ingenious transformation function. But does it justify the price tag? Let's dive in.

The 18+ box art is suitably moody, all dark blues and black, fitting the show's aesthetic perfectly. Inside, you’ll find twenty-two numbered bags, two sticker sheets (yes, 25 stickers – a familiar pain), and a chunky instruction booklet. The designers even included a history of the Creel House and some early concepts for the transformation gimmick. It’s a nice touch, but frankly, after building a few of these 18+ sets, the bonus intros start to feel a bit standard.

Now, the minifigures. Eleven is here, looking ready for business in her season five training outfit. Mike and Dustin are also present, Dustin sporting his Hellfire Club shirt – a nice nod to Eddie Munson. Lucas gets his hospital look, complete with a boombox. These are solid figures, mostly. However, the tan jacket Dustin wears over his Hellfire Club shirt is missing, a strange omission for such a detailed set. And while Eleven's alternate expression is good, her Gatorade bottle accessory feels a bit random. It’s a good cast, but not quite a home run.

The main event, of course, is the Creel House itself. It’s a large model, measuring 50cm wide, and it’s packed with details referencing key moments from the show. The transformation function is genuinely clever, allowing you to flip between the normal and Upside Down versions of the house. It’s a satisfying mechanism that adds a lot of play value and display versatility. You can see the Technic elements that make it work, though some are a bit exposed on the tree models, which is a minor aesthetic quibble.

The set also comes with some decent side builds: Steve’s BMW and Jonathan’s radio van. These add context and characters to the display. The BMW is a nice little car, and the radio van is a fun nod to the show’s investigative side. They aren't the main focus, but they round out the package nicely.

However, we have to talk about the price. At £249.99 / $299.99 on LEGO.com (UK/US, per Brickset), it’s a substantial investment. Per-piece cost is reasonable, but the overall size for that price feels a little… less than expected. When you compare it to other large display sets, it feels a bit stretched. The detail is there, the transformation is great, but the sticker count and some minifigure choices leave you wondering if they could have squeezed more value in.

In India, the LEGO Stranger Things: The Creel House ([11370](/sets/11370-stranger-things-the-creel-house)) is listed at MyBrickHouse for ₹27,999, though it may be out of stock. If this were officially sold in India, it would cost roughly the same as 18 months of Netflix Premium. MyBrickHouse and Toycra are the stores to watch — use code ABHINAV12 for 12% off on orders above ₹500 at Toycra. Expect a 4–6 week lag from global launch if it becomes available.

This set is a must-have for hardcore Stranger Things fans. The transformation mechanism and the sheer detail poured into the Creel House are exceptional. It’s a fantastic display piece that captures the spirit of the show. But for the average LEGO fan, the high price and a few minor flaws might make it a tough pill to swallow. It’s a great set, but it’s also a significant commitment.

Keep building, keep dreaming... And don't let your wallet see your LEGO wishlist.

Priced at ₹27,999 on MyBrickHouse, confirmed in stock as of 21 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

On that bombshell, bubyee.

Corrected 29 Sep 2026: added the source for the UK/US prices (LEGO.com, per Brickset); no figure changed.$boi_t$, updated_at = now()
 WHERE slug = 'lego-stranger-things-the-creel-house-11370-worth-27999' AND md5(content) = '4dd50572f2467b6599d6fe1384653827';

-- lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag
UPDATE public.reviews SET content = $boi_t$Your wallet just sent a panic alert. The 2026 Sea Serpent GWP hides behind a minimum LEGO.com spend that will make any bank balance sweat. LEGO Ideas has resurrected the 1992 castle classic, but this time it arrives as a Gift with Purchase, not a stand‑alone box you can just click “add to cart”.

The set, [40912](/sets/40912-sea-serpent) Sea Serpent, landed on LEGO.com from 7‑12 July 2026 as part of Insiders Days. Spend over the promotion's threshold and the ship appears in your bag. That’s a steep entry fee for a set that, on paper, feels more like a nostalgic trinket than a full‑blown build. The original [6057](/sets/6057-sea-serpent) Sea Serpent was beloved for its massive hull and towering dragon‑like prow; this remake tries to capture that spirit while sprinkling in modern touches.

One of the biggest wins is the new fabric sail. The original fan submission used a brick‑built sail, but LEGO’s Ideas team swapped it for a real textile piece emblazoned with the Black Knights’ dragon sigil. The fabric feels premium, and it instantly upgrades the silhouette. Textile elements are notoriously tricky for LEGO – they require precise stitching and can be pricey to produce – so its inclusion signals that LEGO is serious about delivering a proper homage.

Another highlight is the custom shield printed on the Legend of Zelda Hyrule Shield element. The gold‑tinged background, blue outline, and central dragon sigil make it arguably the most eye‑catching shield in the current Castle lineup. If you ever see it on Pick a Brick, expect the author to snap up a bulk lot.

Where the set falters is in the minifigure department. Only two figures are included, both built from the scale‑mail torso of the Griffin Knights ([21358](/sets/21358-minifigure-vending-machine)) and plain black slacks. The original 1992 version shipped three Black Knight minifigs, one of which wore a printed breastplate. The omission of a third figure feels like a missed opportunity, especially since the Black Falcon minifig – a fan favourite – is absent, even though the torso is retired. Adding a crossbow would have been a nice nod to the original’s siege vibe, but that’s another gap.

From a building perspective, the set isn’t a brick‑heavy marathon. The fabric sail and the shield introduce a couple of new techniques, but the core hull remains a straightforward brick‑wall structure. Builders who love the nostalgia of the old castle will enjoy the familiar shape, while newcomers might find the limited minifig count and lack of accessories underwhelming for the price tag.

Value‑for‑money is the real question. Having to spend that much for a GWP that delivers a single sail, a fancy shield, and two generic minifigs feels stretched. Compare that to other recent Castle releases that include more figures, weapons, and play features for a similar price. If you’re a die‑hard Black Knights fan, the sail and shield alone might justify the cost, but for the average builder the set feels like a collector’s piece rather than a playset.

In short, the 40912 Sea Serpent is a love letter to the past with a few modern upgrades, but it’s hamstrung by a high spend requirement and a sparse minifig lineup. If you can swing the qualifying spend and love the fabric sail, it’s a nice addition to a Black Knights display. Otherwise, you might want to wait for a discount or a more fully‑fledged castle set.

In India, MyBrickHouse has sold the Sea Serpent on its own since 26 Sep 2026 for ₹2,499 — about ₹10 a piece for 241 pieces, with no qualifying spend needed. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra. Expect a 4–6 week lag from global launch.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Priced at ₹2,499 on MyBrickHouse, confirmed in stock as of 29 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

Corrected 29 Sep 2026: removed an unsourced Indian price estimate and an unverified US spend threshold. No Indian retailer listed this GWP when we published.

Updated 29 Sep 2026: this set is now available in India. Verdict revised from IMPORT ONLY to WAIT.$boi_t$, title = $boi_t$LEGO 40912 Sea Serpent GWP (2026): Worth the Spend?$boi_t$, verdict = 'WAIT', updated_at = now()
 WHERE slug = 'lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag' AND md5(content) = 'c27812f49a4130c419b1a9c9253a5f4c';

-- lego-tower-bridge-21067-worth-10300
UPDATE public.reviews SET content = $boi_t$Your wallet just heard the toll of London's Tower Bridge and it’s not happy. The LEGO Architecture [21067](/sets/21067-tower-bridge) Tower Bridge arrives with a price tag that will make you check your EMI calculator twice. That said, the set itself is a love letter to a city that never stops moving, and it delivers a surprisingly satisfying building experience for an Architecture release.

The 21067 version is a step down from the retired [10214](/sets/10214-tower-bridge) Tower Bridge, which had over 4,000 pieces and was on sale from 2010 to 2018. This new incarnation has 3,745 pieces and keeps the iconic twin towers, the bascule leaves, and the sweeping walkways that make the landmark instantly recognizable. The designers have opted for a slightly smaller scale, which means the set fits more comfortably on a desk or a bookshelf without looking cramped.

From a build perspective, the set is a treat. The construction begins with a solid baseplate that anchors the twin towers, each built from a series of interlocking plates that give the illusion of depth without the need for excessive scaffolding. The most rewarding moment arrives when you lock the bascule leaves into place – a clever use of hinge plates that mimics the real bridge’s opening mechanism. The final step, attaching the glass canopy over the central walkway, feels like a polished finish rather than an after‑thought.

Design-wise, the tower silhouettes capture the Victorian grandeur of the original, while the color palette sticks to the muted greys and blues that Architecture sets are known for. The inclusion of tiny lampposts and the occasional red brick detail keeps the model from feeling too bland. If you’re a fan of London or simply enjoy architectural miniatures, the set will sit proudly next to other cityscape pieces without looking out of place.

Value‑for‑pieces is where the set shines. It has 3,745 pieces; no Indian retailer listed it when we published, so we can’t give an honest per-piece figure for that date. The set also includes a set of printed tiles that spell out “Tower Bridge” in a stylized font, adding a collectible touch that Architecture fans have come to expect.

However, the set isn’t without minor drawbacks. The lack of a dedicated display stand means you’ll need to improvise if you want a freestanding presentation. Also, the tiny detailing on the bascule leaves can be a bit fiddly for younger builders, but most adult fans will find it manageable.

Overall, 21067 Tower Bridge delivers a balanced mix of building pleasure, visual appeal, and reasonable piece economics. It captures the spirit of the iconic London landmark without demanding an enormous shelf space or a massive budget.

Check MyBrickHouse for availability. Toycra will likely list it 4–6 weeks after the global launch. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Priced at ₹29,999 on MyBrickHouse and Toycra, confirmed in stock as of 21 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

Corrected 29 Sep 2026: piece counts corrected (this set has 3,745 pieces; the retired 2010 version had over 4,000, per Brickset); removed an unsourced Indian price estimate and the per-piece figure built on it. No Indian retailer listed this set when we published. Verdict revised from BUY NOW to WAIT: the BUY NOW rested on that per-piece figure; since 14 Aug 2026 MyBrickHouse and Toycra list it at its MRP (₹29,999).$boi_t$, title = $boi_t$LEGO Tower Bridge (21067): Worth It?$boi_t$, verdict = 'WAIT', updated_at = now()
 WHERE slug = 'lego-tower-bridge-21067-worth-10300' AND md5(content) = '03bc82969d673497c01b29ff8f835f79';

-- lego-10326-natural-history-museum-review
UPDATE public.reviews SET content = $boi_t$When we published (14 May 2026), Toycra listed the LEGO Icons Natural History Museum at ₹34,999, its official MRP. Since 26 May 2026 MyBrickHouse has listed it at ₹31,999 — ₹3,000 below MRP, the rare case where the cheaper store is under the set's own MRP. That's worth knowing before we discuss anything else about this set.

The Natural History Museum ([10326](/sets/10326-natural-history-museum)) is a 4,015-piece Modular Buildings entry. It is beautiful, and — unusually for this column — it is actually fairly priced right now.

The Natural History Museum recreates the grand Victorian facade of a natural history institution — soaring arched windows, ornate stonework, a cathedral-like entrance hall with a tiled floor. Inside: a fossil display case, a dinosaur skeleton dominating the great hall, a reading room on the upper floor, and a rooftop observatory with a working telescope detail. At 4,015 pieces, it is a full Modular Buildings entry and architecturally one of the more ambitious ones in recent years. The colour scheme — cream, light grey, dark tan — is serious and accurate and exactly what this building should look like.

The build takes 12–16 hours at a comfortable pace and has the satisfying cadence that distinguishes all Modular Buildings sets: section by section, floor by floor, the museum assembles itself in recognisable stages, each one feeling like a small completion before joining the whole. The interior detail is consistent throughout. This is a high-quality LEGO set. The problem is not the set.

MyBrickHouse (since 26 May 2026): ₹31,999. Toycra: ₹34,999. Import duty does not apply — this set is officially stocked in India. Toycra's ₹34,999 is the confirmed official MRP; MyBrickHouse is pricing it ₹3,000 below MRP — the rare case where retailer margin works in your favour rather than against it. In Indian terms: ₹3,000 is about 5 plates of butter chicken for two, or a solid saving without needing to wait for a sale.

WHAT IT SHOULD COST

At MyBrickHouse's ₹31,999 — ₹7.97 per piece for 4,015 pieces of excellent Victorian architecture, already below the official MRP — the verdict is simple: buy without hesitation. There's no reason to wait for a sale when the standing price is already under MRP.

4,015 pieces of Victorian architecture executed with real conviction. A set that earns a BUY at MyBrickHouse's ₹31,999 — already below MRP, no sale required. On that bombshell, your wallet can relax for once.

Priced at ₹31,999 on MyBrickHouse and Toycra, confirmed in stock as of 21 Sep 2026.
Verdict: BUY NOW.

Standard disclaimer: if you've got the money, obviously buy it — that's what the verdict says too, for once we all agree.

Corrected 29 Sep 2026: dated the prices. At publication only Toycra was tracked (₹34,999); MyBrickHouse's ₹31,999 listing began on 26 May 2026.$boi_t$, updated_at = now()
 WHERE slug = 'lego-10326-natural-history-museum-review' AND md5(content) = 'd24eb02f04e1ed34ca87a938454e05cd';

-- lego-40896-the-x-files-scullys-lab-gwp-is-this-a-must-have
UPDATE public.reviews SET content = $boi_t$Your wallet just got an alert: you need to buy the LEGO X-Files diorama, 21369. But wait, there's a catch. The accompanying GWP, [40896](/sets/40896-the-x-files-scullys-lab) Scully's Lab, is only available if you buy the main set during a specific window. In India, though, there's a shortcut: MyBrickHouse sells Scully's Lab on its own.

The LEGO Ideas X-Files diorama ([21369](/sets/21369-the-x-files)) is out now — in stock at MyBrickHouse for ₹19,999 as of 26 Sep 2026 — and with it comes this little bonus: 40896 Scully's Lab. It was a Gift with Purchase: you could only get it by buying the main diorama set between August 1st and August 10th, 2026, and stocks were limited. Jay's Brick Blog warned that these GWPs often sell out fast, much like the Sea Serpent one did.

The GWP itself is a small diorama, just 221 pieces across three bags. It focuses on Agent Scully in her FBI lab. It’s essential for fans, apparently, as Scully spends a lot of screen time doing autopsies. The star here is the exclusive Scully minifigure. She’s got a lab coat, a new head with protective glasses, and an exclusive torso. Plus, a brand-new wig mould designed just for her. It's a solid minifigure, a definite draw for collectors.

The lab itself is compact. You get a small table with a microscope and vial, a sink area with reagent cabinets, and a doughnut. Yes, a doughnut. If you know, you know. The glass cabinets use a neat sliding technique. The back of the model has a fly tile, a nod to an episode featuring a young Aaron Paul. The centrepiece is the examination table, ready for… well, whatever you want to put on it.

You can use minifigures from the main set, like the Grey Alien, for Scully to investigate. Or, raid your entire LEGO collection for some unique autopsy subjects. The set captures the vibe of Scully’s forensic work.

In India, MyBrickHouse sells Scully's Lab on its own for ₹1,999 — about ₹9 a piece for 221 pieces, with no main-set purchase needed.

The verdict? If you're buying the main X-Files set from LEGO.com or a LEGO Store between August 1st and 10th, 2026, and you can snag this GWP, do it. It’s a nice little companion piece with a great minifigure. For us in India, MyBrickHouse has it at ₹1,999, its full listed price, so there's no rush — it's a nice extra rather than a must-grab.

Priced at ₹1,999 on MyBrickHouse, confirmed in stock as of 26 September 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Updated 27 Sep 2026: this set is now available in India. Verdict revised from IMPORT ONLY to WAIT. Main set 21369 status updated: in stock at MyBrickHouse (₹19,999). The 1–10 Aug promo is now described in the past tense.

Corrected 29 Sep 2026: removed narration of a source review; no price or count changed.$boi_t$, updated_at = now()
 WHERE slug = 'lego-40896-the-x-files-scullys-lab-gwp-is-this-a-must-have' AND md5(content) = 'c6f728d65efe1cd5b7c217d6c392dde8';

-- lego-gremlins-gizmo-and-stripe-40919-worth-3300
UPDATE public.reviews SET content = $boi_t$Your wallet is already preparing for impact. LEGO’s BrickHeadz line isn't always a home run, but when it hits, it hits. The latest entry, [40919](/sets/40919-gremlins-gizmo-and-stripe-figures) Gremlins: Gizmo and Stripe, looks like a definite home run, capturing two iconic movie characters with surprising accuracy for the blocky format. It’s a fantastic addition for fans of the franchise, and frankly, some of the best BrickHeadz we’ve seen in a while.

The Brickset review highlights just how much attention to detail went into these two figures. Gizmo, the adorable Mogwai, is instantly recognizable. The designer even managed to nail those tiny eyelids, a detail that makes all the difference. The choice of light nougat for his "skin tone" is spot on, and the curved tile for his mouth, while simple, works. His popcorn bucket accessory, while a reuse, is fitting.

But it's Stripe, the mischievous monster, who truly steals the show. The combination of earth green and brick yellow is striking, and the printing on his arms and eyebrows adds a lot of character. The real masterstroke, though, is the use of a rock element for his chin – it’s a clever piece of building that perfectly captures Stripe’s menacing look. The red BrickHeadz eyes are also a great touch, especially considering their recent appearance on the Megatron figure. And that mohawk? Absolutely fantastic.

Seeing these figures alongside the larger [21361](/sets/21361-gremlins-gizmo) Gremlins: Gizmo set and the Dimensions minifigures really drives home how well LEGO has captured the Gremlins spirit across different formats. The only minor gripe is Gizmo's accessory, and that’s nitpicking in an otherwise stellar package. These are, without a doubt, some of the best BrickHeadz to date.

The build experience itself is described as satisfying, with interesting shaping and clever use of parts. The piece count is 230, which is decent for two BrickHeadz, and the price per piece is quite competitive. For fans of the Gremlins movies, this is an absolute must-have. It’s a rare case where the BrickHeadz format feels genuinely perfect for the characters.

On LEGO.com it's US$24.99 / £19.99 (per Brickset); no Indian retailer listed it when we published. MyBrickHouse and Toycra will likely stock this 4–6 weeks after the global launch. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.

This set is more than just a couple of cute brick figures; it's a celebration of a beloved franchise. The accuracy, the clever building techniques, and the sheer charm of these two characters make 40919 a standout release. If you’re a Gremlins fan, or just appreciate excellent BrickHeadz design, don’t hesitate.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: this review was linked to the wrong catalogue set, so it showed that set's price. It now links to 40919. Also removed an unsourced Indian price estimate and narration of a source review; added LEGO.com's US/UK prices (per Brickset). Verdict revised from BUY NOW to IMPORT ONLY: the BUY NOW rested on that estimate, and no Indian retailer has listed this set.$boi_t$, title = $boi_t$LEGO Gremlins: Gizmo and Stripe (40919): Worth It?$boi_t$, verdict = 'IMPORT ONLY', set_id = 'df526224-f674-4291-9f82-91ab829221e0', updated_at = now()
 WHERE slug = 'lego-gremlins-gizmo-and-stripe-40919-worth-3300' AND md5(content) = '98026f1778d7b86a67d2eeacde4c84fe';

-- lego-city-police-train-heist-60508-19999-for-a-cat-and-mouse
UPDATE public.reviews SET content = $boi_t$Your wallet just called. It wants to know if chasing down a LEGO train is really worth ₹19,999. The LEGO City Police Train Heist ([60508](/sets/60508-police-train-heist)) has landed, and while it’s a proper monster of a set with 1,313 pieces, that price tag is going to make a lot of you hesitate. For this kind of money, you’re not just buying bricks; you’re buying an experience, and we need to see if this particular chase is worth the pursuit.

This set brings the classic cops-and-robbers theme to the rails. You get a motorized train, complete with a locomotive, a prison car, a flatbed carrying a rally car, and another flatbed with a bank safe. The bad guys have a helicopter with a working claw – classic stuff. The good guys? A police officer, a detective, the train driver, and three crooks. The whole setup includes an oval track with a railroad crossing and a re-railing piece, which is a nice touch for train fans. The train itself is Powered Up compatible, meaning you can control it via remote or the LEGO Builder app. That’s a big plus for anyone who likes their LEGO creations to move.

The build itself sounds like a solid City experience. You’re getting a substantial train, which is always satisfying to assemble. The app-guided building is there for those who prefer digital instructions, and the 1,313 pieces mean you’re unlikely to finish it in a single afternoon. The play features are standard for a LEGO City police set: the helicopter’s claw trying to snatch the safe, the rally car being transported, and the prison cell ready to hold the apprehended villains. It’s all about imaginative play, and for younger builders aged 7 and up, this will likely hit all the right notes.

However, the elephant in the room is the price. ₹19,999 is a significant investment. For that amount, you could get a couple of much smaller, but perhaps more intricate, Creator Expert or Technic sets. Or, you could buy a decent mid-range smartphone. The value proposition here hinges heavily on how much you or your child values a motorized train and the specific play scenarios it offers. The piece count is good, but the price-per-piece ratio isn't exactly a bargain.

Looking at the set, it’s a competent execution of a familiar theme. The train looks decent, the accessories are fun, and the motorized aspect adds a lot of playability. But does it justify that ₹19,999 price point? It’s a tough call. If you’re a hardcore LEGO City fan, especially one who loves trains, this might be an auto-buy. The motorized functionality is a big draw. But for the casual builder, or someone looking for the best bang for their buck in terms of pure brick value or display aesthetics, there might be better options out there. It feels like a premium set in a theme that usually offers more accessible price points.

It’s a solid, playable set with good features, but the high price means you really need to want this specific train heist scenario. It’s not a must-have for everyone, but for the right fan, it’s a big, exciting addition to their LEGO City.
Priced at ₹19,999 on MyBrickHouse and Toycra, confirmed in stock as of 9 Sep 2026. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: WAIT. Good set, but the price will drop.

Corrected 29 Sep 2026: removed a stray "BUY NOW" line that contradicted this review's verdict (WAIT).$boi_t$, updated_at = now()
 WHERE slug = 'lego-city-police-train-heist-60508-19999-for-a-cat-and-mouse' AND md5(content) = '36b86ca5e1929105ba5cf594a6be9739';

-- lego-avengers-tower-76269-worth-39199
UPDATE public.reviews SET content = $boi_t$Your wallet just screamed. Mine did too. The LEGO Marvel Avengers Tower ([76269](/sets/76269-avengers-tower)) has landed in India and it's exactly as enormous and expensive as you'd expect. At 5,201 pieces and standing over 35 inches tall, this isn't just a set; it's a commitment. A very, very expensive commitment.

The original price of ₹48,999 has been slashed by 20%, bringing it down to a still eye-watering ₹39,199. That's a significant discount, mind you. But let's be real, is it enough to make this tower a must-buy right now? We need to dig deeper than the sticker shock.

This set aims to recreate the iconic Avengers Tower, and on that front, it largely succeeds. The sheer scale is impressive, and the ability to open up sections of the building to reveal detailed interiors is a nice touch. You get over thirty minifigures, which is frankly insane. We're talking Iron Man, Captain America, Thor, Hulk, Black Widow, Nick Fury, and a host of others. The inclusion of specific scenes like the lab investigation of Loki's scepter and Captain America's glass walkway fight adds a lot of playability and display potential for any Marvel fan worth their salt.

The build experience itself is described as rewarding, with digital instructions available on the LEGO Builder app alongside the printed booklet. For adult fans who appreciate intricate models and cinematic callbacks, this set offers a deep dive into the MCU. The accessories are plentiful, from the Tesseract to Thor's hammer and a pager for Captain Marvel. It’s clear LEGO has packed this set with fan service.

However, the price, even with the discount, remains a massive hurdle. ₹39,199 is a substantial amount of money. While the piece count is high and the minifigure selection is stellar, the value proposition still feels a bit stretched. Is it a fantastic display piece? Absolutely. Is it a fun build? I'm sure it is. But the cost means it’s not an easy recommendation for everyone.

The discount is substantial, and the fact that it's readily available in India through MyBrickHouse and Toycra is a huge plus. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra. No importing headaches, no waiting for weeks. You can have this behemoth on your shelf relatively quickly. But even with 20% off, you're still looking at a serious investment. This is the kind of set you save up for, or perhaps pool resources with a friend. It's a luxury item, no doubt about it.

For the ultimate Marvel fan with deep pockets and a dedicated display space, this is probably a BUY NOW. The sheer amount of detail and the incredible minifigure count are hard to ignore, especially at this reduced price. But for the average LEGO fan who watches the MCU and enjoys building, it might be prudent to WAIT. See if further discounts appear, or if the initial hype dies down. The value is there, but it's on the very high end of LEGO pricing.

Priced at ₹39,199 on MyBrickHouse and Toycra, confirmed in stock as of 16 Sep 2026.
Verdict: WAIT.

Standard disclaimer: rich readers can skip the verdict and just buy it. We'll be over here checking if MyBrickHouse's HDFC EMI discount makes this hurt less.

The build quality is, as always with LEGO, top-notch. The structural integrity of such a tall model is impressive, and the design team has clearly put a lot of effort into making it both stable and visually appealing. It’s a landmark model designed for adults, and it delivers on that promise of an immersive, satisfying build. The inclusion of a Quinjet and other vehicles adds to the overall presentation.

So, the verdict? It's a difficult one. The set is objectively amazing in terms of detail, minifigures, and scale. The discount is significant. But the price point remains daunting. If you're a die-hard Marvel fan and the budget allows, go for it. If you're on the fence, or if that price tag is making your eyes water, it's probably best to wait for another sale or consider other options. This is a purchase that requires careful consideration, not just a quick click.

Keep building, keep dreaming... And don't let your wallet see your LEGO wishlist.

Verdict: WAIT. Good set, but the price will drop.

On that bombshell, bubyee.

Corrected 29 Sep 2026: minifigure count made non-specific: Rebrickable lists 31 and Brickset 32.$boi_t$, updated_at = now()
 WHERE slug = 'lego-avengers-tower-76269-worth-39199' AND md5(content) = '558e63b15ba91a5cb4a48b2b1c0298aa';

-- lego-darth-vaders-lightsaber-40897-worth-the-import-price
UPDATE public.reviews SET content = $boi_t$Just 174 pieces, but the pain of wanting something you can't easily get is universal. LEGO has dropped another life-size prop replica with [40897](/sets/40897-darth-vaders-lightsaber) Darth Vader's Lightsaber, and if you're a Star Wars fan with a penchant for display pieces, your wallet is already bracing for impact. The problem? It's not officially coming to India.

This isn't just any lightsaber; it's the lightsaber. The one that defined a generation of villainy. While the source material might show minor variations across films, this model leans towards the Obi-Wan Kenobi series version, with a slightly shorter grip and distinct activator details. It’s instantly recognisable, and LEGO’s execution here is, dare I say, superb. The proportions feel right, and it’s sturdy enough to handle without fear of it falling apart. If you've collected the other life-size sabers, like [40917](/sets/40917-the-darksaber) The Darksaber or [40730](/sets/40730-luke-skywalkers-lightsaber) Luke Skywalker's Lightsaber, this will fit right in.

The build focuses on 4x4 round elements, forming the core of the hilt. LEGO has done a commendable job with the details. The emitter shroud, using those curved Technic panels, is a neat trick that replicates the on-screen prop's shape almost perfectly. Even the activator dial has deliberately exposed studs to mimic the original prop's texture. A nice touch is the inclusion of two trans-red 2x2 round bricks representing the kyber crystals, a nod to the lore that Vader's lightsaber houses two. The display stand is simple but effective, allowing the saber to be displayed in either direction and featuring the standard printed plaque.

Now, for the nitpicks. On screen, Vader's lightsaber has six or seven black handgrips; this model has eight. I can see it being a compromise for a smoother look, but it's still a deviation from the prop.

The biggest frustration, however, is its availability. This set is positioned as a gift-with-purchase for the rather colossal [75457](/sets/75457-executor-super-star-destroyer) Executor Super Star Destroyer. That's a massive spend threshold. And even then, it's only available in select markets. This "limited availability" is a common LEGO tactic that leaves many fans feeling left out, especially those outside the primary markets.

It isn't sold on its own: Brickset lists it as a gift with purchase with 75457 at LEGO.com in October 2026, so there's no retail price to convert into rupees. No Indian stores like Toycra or MyBrickHouse have it listed, and it's unlikely they will unless LEGO India decides to officially release it here. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission). For now, it's import only.

This set is a fantastic display piece for any Star Wars fan. The build is solid, the design is accurate save for a minor grip count quibble, and it fits perfectly into the growing collection of lightsaber replicas. If you can get your hands on it without breaking the bank through unofficial channels, it's definitely worth it. But for us in India, the price and the hassle of importing make it a tough proposition.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Updated 27 Sep 2026: opening corrected. It began with another set's specs ("ten thousand pieces, five feet tall") before admitting that wasn't this set; 40897 has 174 pieces (Brickset). Also corrected 27 Sep 2026: removed a stray "BUY NOW" line that contradicted the IMPORT ONLY verdict; restated the handgrip nitpick in our own voice (it had narrated an unnamed reviewer, and a claim about the 2021 Luke Skywalker lightsaber that rested on that reviewer was removed); removed an unsourced "US retail price $99.99" and its rupee conversion, because Brickset lists 40897 as a LEGO.com gift with purchase with no retail price.

Corrected 29 Sep 2026: this review was linked to the wrong catalogue set (40483, Luke Skywalker's Lightsaber). It now links to 40897.$boi_t$, set_id = 'f89bdd1b-db58-4e0c-a755-e47901f246f5', updated_at = now()
 WHERE slug = 'lego-darth-vaders-lightsaber-40897-worth-the-import-price' AND md5(content) = 'daeb69a84dab600de2692129669c9f35';
