-- boi:issue 246
-- boi:backup-tables public.news_articles public.reviews
-- boi:expect-before select (select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-40908-restaurants-of-the-world-greece-gwp-coming-august','a4a7afe2ea614ffcf4e3a1263382bd0b'), ('lego-40908-restaurants-of-the-world-greece-gift-with-purchas','2ba988f0e1b97d14a5d0a185b89c9e53'), ('lego-40908-restaurants-of-the-world-greece-gwp-get-it-before','46934b9a3996e1eff0ddeb550c0d9c9d'), ('returning-lego-gwps-in-july-2026-vary-by-region','b6c157587de3f608342b0e955266e252'), ('lego-40899-astro-bot-revealed-as-a-playstation-gift-with-pur','0bbc1d08840461196339dc4f294aaddb'), ('lego-40899-astro-bot-gwp-officially-unveiled-arrives-october','089c4a9b7ab1edc9b2da57d69190b61d'), ('late-august-2026-lego-gwps-grond-steering-wheel-and-botanica','9071f7c4f25001e4a21888979dd109a9'), ('lego-40902-tribute-to-leonardo-da-vinci-gwp-news-what-it-mea','77e13381c10dd46403473ff10a41f3ba'), ('lego-40902-tribute-to-leonardo-da-vinci-gwp-worth','cd8c222c7fe3ba229e90ec96ae02c683'), ('lego-40912-sea-serpent-gift-with-purchase-revealed','1de8c0af6bb51873bfcad810c8979974'), ('lego-koenigsegg-sadairs-spear-steering-wheel-40894-gwp-funct','9d65f2cf9c9d1f804e97ad62440d4dab'), ('lego-xfiles-scullys-lab-40896-gwp-review-is-it-worth-the-cha','df220e542df8f5c4bae53d24f34726a0'))) + (select count(*) from public.reviews where (slug, md5(content)) in (values ('lego-restaurants-of-the-world-greece-40908-a-charming-gwp-wo','e1371b990c0d25e98c857f6a16e65359'), ('lego-ministry-munchies-the-daily-prophet-stands-40901-compan','be1e89791e4da035b18e33b800405bc8'), ('lego-tribute-to-leonardo-da-vinci-40902-worth-19600','f0e2b6f2f2240e9398f782f679708cd9'), ('lego-darth-vaders-lightsaber-40897-worth-the-import-price','daeb69a84dab600de2692129669c9f35'))) = 16 and exists (select 1 from public.store_prices where set_id = '40894' and store_id = 'mybrickhouse' and price_inr = 2499 and in_stock = true) and exists (select 1 from public.store_prices where set_id = '40912' and store_id = 'mybrickhouse' and price_inr = 2499 and in_stock = true) and exists (select 1 from public.store_prices where set_id = '40893' and store_id = 'mybrickhouse' and price_inr = 2999 and in_stock = false) and exists (select 1 from public.store_prices where set_id = '40902' and store_id = 'mybrickhouse' and price_inr = 2499 and in_stock = false) and exists (select 1 from public.store_prices where set_id = '40896' and store_id = 'mybrickhouse' and price_inr = 1999 and in_stock)
-- boi:expect-after select (select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-40908-restaurants-of-the-world-greece-gwp-coming-august','a24ae0baff4cc5215af6db0b6f829039'), ('lego-40908-restaurants-of-the-world-greece-gift-with-purchas','c2799e8fc0cc548ecabce975b5fc51da'), ('lego-40908-restaurants-of-the-world-greece-gwp-get-it-before','b14d04e8c0998128c53f2e2ade0ef177'), ('returning-lego-gwps-in-july-2026-vary-by-region','eacc5343caaef8806479bd0a5dff3a87'), ('lego-40899-astro-bot-revealed-as-a-playstation-gift-with-pur','2a33250c5da23692d25d60f14389b377'), ('lego-40899-astro-bot-gwp-officially-unveiled-arrives-october','429ce2136e191cb68576b4c149694735'), ('late-august-2026-lego-gwps-grond-steering-wheel-and-botanica','54f6d8a45da6658d11fa1ba2cb08ad73'), ('lego-40902-tribute-to-leonardo-da-vinci-gwp-news-what-it-mea','e4706e85632c014a93de298b731b144c'), ('lego-40902-tribute-to-leonardo-da-vinci-gwp-worth','a35fb7d60c0402f629c89d89a01aa964'), ('lego-40912-sea-serpent-gift-with-purchase-revealed','91f7553ee008e63fa0b5fc087402ae4e'), ('lego-koenigsegg-sadairs-spear-steering-wheel-40894-gwp-funct','2435c9a26c968afddeed9e401335592c'), ('lego-xfiles-scullys-lab-40896-gwp-review-is-it-worth-the-cha','c3c011008b97def48d6122e79820bd8a'))) + (select count(*) from public.reviews where (slug, md5(content)) in (values ('lego-restaurants-of-the-world-greece-40908-a-charming-gwp-wo','a2cb9662e535608303864f0c85125e54'), ('lego-ministry-munchies-the-daily-prophet-stands-40901-compan','0e93896b4296dc76a23c8ce8bbb57aa1'), ('lego-tribute-to-leonardo-da-vinci-40902-worth-19600','bac789c5b1db6524ca91debfa14116f3'), ('lego-darth-vaders-lightsaber-40897-worth-the-import-price','471555c84d42125b39f5fc810f125173'))) = 16
-- #246 batch 2 (P11 item 2, approved into the batches): 16 articles (12 news, 4 reviews) with gift-with-purchase
-- price claims or invented estimates, corrected in place with dated notes (G16); nothing removed. Found by the #429
-- scan. The three 40900 pages are in #428; the 40912 / 40896 reviews are in batch 1 (#412). Store facts quoted
-- ('as of 29 Sep 2026') are guarded above: if a listing changed before this runs, the batch refuses and is rebuilt.
-- Generated by boi-db-backups/2026-09-29-246-batch2/build_batch2.py from before.json.
-- lego-40908-restaurants-of-the-world-greece-gwp-coming-august
UPDATE public.news_articles SET content = $boi_t$Your wallet called. It wants to discuss the upcoming LEGO [40908](/sets/40908-restaurants-of-the-world-greece) Restaurants of the World: Greece GWP. It's a freebie, sure, but only if you spend enough to make your bank account weep. The GWP requirement is set at a hefty US$180 / £160 / €180. That's a lot of bricks for a free gift.

This Greek taverna GWP is the third in a quarterly series celebrating global cuisine. It's a charming little build, apparently inspired by coastal towns like Santorini and Mykonos. We're talking whitewashed walls, a splash of blue on the sign, and even a tiny kitchen area. For the music lovers, there’s a lute element representing a bouzouki. And because no Greek scene is complete without them, a kitten is included. You also get an exclusive minifigure sporting a traditional Greek tunic. It’s a nice touch, adding to the authenticity of the miniature Mediterranean dining experience.

The series has already taken us to Mexico and Japan. With Greece now confirmed, the speculation for the fourth and final GWP is already running wild. Will it be an Italian trattoria? A French bistro? A North American diner? LEGO's keeping us guessing, but the possibilities are endless, and frankly, a little delicious. Anyone who has visited Greece will surely appreciate the nod to the ubiquitous family-run tavernas and the roaming cats that are a staple of the landscape. This GWP aims to capture that essence.

The promotion runs from 11-20 August 2026. It’s a limited-time offer, so if you’re planning to pick up any of the new August 2026 releases, this might be the perfect opportunity to snag a bonus set. Just remember the minimum spend to qualify. It’s all about that strategic shopping.

40908 is a gift with purchase: it isn't sold separately, so it has no retail price in India or anywhere else. You get it free with a qualifying LEGO order while the promotion runs (the US$180 / £160 / €180 spend above), and no Indian retailer lists it.

This GWP is a nice addition for collectors of the series and those who appreciate detailed miniature builds. The execution looks solid, and the theme is undeniably appealing. Just be mindful of the spend requirement; it’s not a cheap add-on.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version turned the US$180 spend requirement into an "estimated import price" of ₹23,700, and its WAIT verdict said "the price will drop". 40908 is a gift with purchase that isn't sold separately, so the figure is removed and the verdict is now IMPORT ONLY.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.$boi_t$
 WHERE slug = 'lego-40908-restaurants-of-the-world-greece-gwp-coming-august' AND md5(content) = 'a4a7afe2ea614ffcf4e3a1263382bd0b';

-- lego-40908-restaurants-of-the-world-greece-gift-with-purchas
UPDATE public.news_articles SET content = $boi_t$The LEGO Insiders program is getting a taste of the Mediterranean. Brickset revealed the latest gift-with-purchase, [40908](/sets/40908-restaurants-of-the-world-greece) Restaurants of the World: Greece, and it’s designed to look like a traditional taverna. Think whitewashed walls and blue accents, a definite nod to island destinations like Santorini. This GWP will be available starting August 11th for LEGO Insiders.

The European purchase threshold is set at €180, which Brickset estimates will translate to around £160 in the UK or $180 USD. This puts it in the mid-to-high range for GWPs, so you’ll need to plan your purchases carefully to snag this one. While some fans are delighted with the Greek theme, others are already comparing it to previous entries in the series, with mixed reactions. Some find it less detailed than prior sets, while others appreciate the distinctively Greek architectural style.

The community discussion highlights a common LEGO GWP dilemma: how much do you spend to get it? With a €180 threshold, it’s a significant commitment. This isn't a small impulse buy; it requires a substantial LEGO haul. Fans are debating whether the set’s charm justifies the spending requirement, especially when compared to other potential GWPs or just the sets they actually want. It’s a classic case of wanting the freebie versus needing the main purchase.

40908 is a gift with purchase: it isn't sold separately, so it has no retail price in India or anywhere else. You get it free with a qualifying LEGO order while the promotion runs (the €180 threshold above), and no Indian retailer lists it.

While the concept of themed restaurants is appealing, the execution and the high spending threshold will be the deciding factors for many. It’s a cute addition to the series, but whether it’s worth clearing out your LEGO wishlist to obtain it remains to be seen.

Keep building, keep dreaming... And don't let your wallet see your LEGO wishlist.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version treated the $180 spend threshold as a retail price and estimated an import price of ₹22,100, and its WAIT verdict said "the price will drop". 40908 is a gift with purchase that isn't sold separately, so the figure is removed and the verdict is now IMPORT ONLY.

On that bombshell, bubyee.$boi_t$
 WHERE slug = 'lego-40908-restaurants-of-the-world-greece-gift-with-purchas' AND md5(content) = '2ba988f0e1b97d14a5d0a185b89c9e53';

-- lego-40908-restaurants-of-the-world-greece-gwp-get-it-before
UPDATE public.news_articles SET content = $boi_t$Your wallet can breathe easy. LEGO just dropped the [40908](/sets/40908-restaurants-of-the-world-greece) Restaurants of the World: Greece, the third in a series of four collectable gifts with purchase this year. We've only just seen the review, and the clock is ticking fast – you've only got until August 20th to snag this one directly from LEGO.com. This is a 254-piece set, and while it might not hit the dizzying heights of its predecessors, it's still a charming little build.

The Greek restaurant sits on a 10x12 baseplate. At the front, you get a small table for al fresco dining. The back has a basic prep area, complete with a single stove ring, a worktop, and some storage. It looks like they're whipping up waffles and orange juice in there, which is… a choice. Just three stickers are in the set, one of which decorates the area under the hob. Unlike the Japanese and Mexican restaurants in the series, this one features a bench-style seat facing outwards, positioned behind a table laden with fish, a wine glass, and a fork. There’s even a bowl of water for the obligatory LEGO cat. The proprietor sports a traditional embroidered shirt with the Greek phrase ΚΑΛΗ ΟΡΕΞΗ printed on the back, a local way of saying 'enjoy your meal'.

The stairs on the side lead absolutely nowhere, a typical architectural flourish for the region. While they might seem like wasted space, the actual building footprint is the same 8x10 as the other restaurants in the series. It's shorter in height than the others, and has fewer pieces overall, but it does display well alongside them. If you’re collecting the whole set, this is a must-have.

40908 is a gift with purchase: it isn't sold separately, so it has no retail price in India or anywhere else. You get it free with a qualifying LEGO order while the promotion runs, and no Indian retailer lists it.

Given the limited availability window and the fact it's a gift with purchase, grabbing it directly from LEGO.com is your best bet. Waiting for it to appear on secondary markets or potentially discounted at local stores might mean missing out entirely. If you're invested in the series, don't delay.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹2,500 and two WAIT verdict lines, one saying "the price will drop". 40908 is a gift with purchase that isn't sold separately, so the figure and the stray line are removed and the verdict is now IMPORT ONLY.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.$boi_t$
 WHERE slug = 'lego-40908-restaurants-of-the-world-greece-gwp-get-it-before' AND md5(content) = '46934b9a3996e1eff0ddeb550c0d9c9d';

-- lego-restaurants-of-the-world-greece-40908-a-charming-gwp-wo
UPDATE public.reviews SET content = $boi_t$Your wallet is probably safe this month, but your Instagram feed might be missing out. LEGO’s latest Restaurant of the World Gift With Purchase (GWP), the Greece set ([40908](/sets/40908-restaurants-of-the-world-greece)), is here, and it’s a charming little slice of the Mediterranean. It joins its Mexico and Japan siblings in a quarterly series that’s been surprisingly popular. This one lands as a freebie when you spend US$180 / AU$295 / £160 / €180 or NZD$320 on LEGO.com, but only until August 20, 2026, or while stocks last. That spending threshold is quite steep, pushing this into the territory of needing a significant LEGO purchase just to snag the freebie.

The star of the show, as with previous GWPs in this line, is the exclusive minifigure. This time, it’s a restaurant owner sporting a traditional Greek tunic. The detail on the torso is excellent, with fabric texture and a neat blue trim. Flip it around, and you’ll find a mosaic of a fish – a clear nod to the restaurant’s speciality – alongside some Greek characters that translate to "enjoy your meal." It’s a lovely touch, and a feature LEGO could easily incorporate more often.

The model itself is a picturesque depiction of a traditional Greek Tavern. The classic white and blue colour scheme immediately brings to mind coastal towns like Santorini. The architecture is well-executed, with charming stairs on the side adding visual interest and a unique silhouette. A stickered sign proudly reads "TABEPNA" (Taverna), and a brick-built oversized fish sign reinforces the grilled fish theme. The addition of a trellis with vibrant pink flowers and leaves adds a splash of colour and Mediterranean flair.

Inside, the detailing continues. A bright blue table is set with a cup of coffee and some sunflower seeds. And in a stroke of genius that acknowledges a ubiquitous part of Greek street life, there’s a tiny brown kitten. The set is practically designed for this little feline, with plenty of nooks and crannies, like a small archway window and a dedicated enclave under the restaurant's address. It’s these small, thoughtful details that elevate a GWP from a mere freebie to something genuinely delightful.

The interior is compact, featuring a small kitchenette with a stove, olive oil, and a slice of orange. Hanging on the wall is a Bouzouki, a traditional Greek lute, adding another layer of cultural authenticity. While the interior space is tighter than in previous Restaurants of the World sets, it doesn't detract from the overall charm. Displayed alongside its predecessors, the Greece set fits perfectly, showcasing the design team’s ability to create distinct yet cohesive models. This series has been one of LEGO’s better GWP offerings recently, and with only one more quarter to go, it’s been a consistently strong run.

The main hurdle here is the GWP threshold. Spending $180 USD (roughly ₹15,000) on LEGO to get this set is a significant commitment. If you were already planning a large purchase from the August 2026 releases, then this is a fantastic bonus. However, buying solely to acquire the GWP might be a stretch for many.

40908 is a gift with purchase: it isn't sold separately, so it has no retail price. The US$180 spend is simply the qualifying threshold to get one, and no Indian retailer lists it.

For the set itself, it’s a solid 4 out of 5. The design is charming, the minifigure is exclusive and well-detailed, and the cultural nods are appreciated. It’s a great little display piece. The verdict is IMPORT ONLY: it isn't sold in India, and unless you’re already making a substantial LEGO purchase that qualifies you for this GWP, the high spending requirement makes it hard to recommend chasing it. It’s a lovely freebie, but not worth breaking the bank for.

Keep building, keep dreaming... And don't let your wallet see your LEGO wishlist.
WAIT

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version turned the US$180 spend threshold into an "estimated import price" of ₹17,300, and its WAIT verdict said "the price will drop". 40908 is a gift with purchase that isn't sold separately, so the figure is removed and the verdict is now IMPORT ONLY.

On that bombshell, bubyee.$boi_t$, verdict = $boi_t$IMPORT ONLY$boi_t$, updated_at = now()
 WHERE slug = 'lego-restaurants-of-the-world-greece-40908-a-charming-gwp-wo' AND md5(content) = 'e1371b990c0d25e98c857f6a16e65359';

-- returning-lego-gwps-in-july-2026-vary-by-region
UPDATE public.news_articles SET content = $boi_t$LEGO is bringing back some previous Gifts with Purchase (GWPs) in July 2026, but here’s the catch: what you get depends entirely on where you live. This is likely a move to clear out leftover stock, which is good news if you missed out on a particular freebie. For fans in the US and Canada, the popular [40906](/sets/40906-restaurants-of-the-world-japan) Restaurants of the World: Japan set is returning. You’ll need to spend US$180 or more between July 13-23 to snag it, while stocks last.

Across the pond in the UK and EU, the offer is different. From July 13-16, you can get the [40774](/sets/40774-classic-animation-scenes) Classic Animation Scenes GWP with a minimum spend of £115 or €130. Meanwhile, our friends in Australia and New Zealand get the [40916](/sets/40916-floral-picture-frame) Floral Picture Frame GWP for spending AU$245 or NZD$265 between July 13-23.

There’s also a global offer: a [30731](/sets/30731-tom-nook-and-flying-present) Tom Nook and Flying Present polybag. This one requires a US$50 spend on specific themes like Animal Crossing, Sonic the Hedgehog, Super Mario, The Legend of Zelda, Fortnite, or Minecraft. This offer runs from July 13-23.

The problem for us in India? None of these specific GWPs are listed for our region. While these promotions are running in other parts of the world, Indian fans are left out in the cold. This means the only way to get your hands on these particular GWPs would be through unofficial channels or if you happen to be traveling abroad during the promotion period.

These are gifts with purchase: none of them is sold separately, so there's no retail price to convert. The US$180 figure is the spend needed to get 40906, not its price. MyBrickHouse and Toycra don't stock these promotions, and availability in India is currently none.

It’s a bit of a bummer when these promotions are geographically restricted. We’ll have to keep our eyes peeled for any potential local offers or hope that some of these GWPs eventually make their way to India through official channels, though that seems unlikely based on this announcement. For now, it’s a case of watching from the sidelines.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version turned the US$180 minimum spend for 40906 into an "estimated import price" of ₹25,000. Gifts with purchase have no retail price; the figure is removed.

On that bombshell, bubyee.$boi_t$
 WHERE slug = 'returning-lego-gwps-in-july-2026-vary-by-region' AND md5(content) = 'b6c157587de3f608342b0e955266e252';

-- lego-40899-astro-bot-revealed-as-a-playstation-gift-with-pur
UPDATE public.news_articles SET content = $boi_t$LEGO just announced the [40899](/sets/40899-astro-bot) Astro Bot, and your wallet is already twitching nervously. This isn't a set you can just buy off the shelf, though. It’s a gift-with-purchase, meaning you'll need to spend a certain amount to get it. The rumour mill suggests that threshold is $150, which is a significant chunk of change.

The 276-piece model depicts Astro Bot, the PlayStation mascot. It looks pretty good from the images available, with some nice detail and swappable eye tiles for different expressions. It’s a neat idea, especially for fans of the PlayStation ecosystem. Whether it ends up being tied to a PlayStation console purchase or a general $150 spend is still up in the air, with conflicting reports circulating. We should know for sure within the next few days.

This GWP is set to launch on October 1st. For those of you who are deep into the LEGO collecting game, this might be a must-have. It’s a unique item, and GWPs often become quite sought after. However, it’s also a reminder that LEGO and Sony are leaning into the gamer demographic, which is a smart move given the overlap in fan bases.

The question remains whether this will ever see an official release in India. Historically, GWPs don't always make it to our shores through official channels, often requiring import or a trip abroad. As a gift with purchase, 40899 isn't sold on its own anywhere, so it has no retail price.

Because it has no price of its own, there's no import cost to estimate. Neither Toycra nor MyBrickHouse is expected to stock it, which makes it import only for now.

It’s a cool looking model, no doubt. But as a GWP, its availability in India is highly questionable. If you absolutely must have it, prepare to pay a premium on the secondary market or through unofficial channels.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version gave 40899 a US retail price of $150 and an estimated import cost of ₹19,300. 40899 is a gift with purchase with no retail price; both figures are removed.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.$boi_t$
 WHERE slug = 'lego-40899-astro-bot-revealed-as-a-playstation-gift-with-pur' AND md5(content) = '0bbc1d08840461196339dc4f294aaddb';

-- lego-40899-astro-bot-gwp-officially-unveiled-arrives-october
UPDATE public.news_articles SET content = $boi_t$LEGO has officially pulled back the curtain on [40899](/sets/40899-astro-bot) Astro Bot, a new Gift with Purchase (GWP) set slated for release on October 1st, 2026. This little bot is a nod to the critically acclaimed PlayStation 5 game, where players control a charming robot on a mission. It’s shaping up to be one of the stronger GWPs LEGO has offered this year, adding a bit of gaming flair to the brick-built world.

The Astro Bot GWP is expected to be a freebie with qualifying purchases of US$150 or more, starting from October 1st. While there have been some whispers about it being exclusively bundled with the upcoming [72306](/sets/72306-playstation) PlayStation set, that scenario seems unlikely. However, if you’re already planning to grab the 72306 PlayStation, which also launches on October 1st for US$179.99, you’ll comfortably meet the GWP threshold. The 72306 PlayStation itself is priced at US$179.99, AU$279.99, £139.99, €159.99, CAD$239.99, and SGD$239.90.

This Astro Bot model looks genuinely delightful. It captures the essence of the game character, a cute robot tasked with rebuilding his spaceship, which itself is shaped like a PlayStation. For fans of modern platformers, this GWP is a welcome addition, celebrating a game that's been lauded as one of the best of its generation. It’s a smart move by LEGO to tap into the gaming community, especially with a beloved character like Astro Bot.

More details on exact purchase thresholds and availability in India are still pending official confirmation. We’ll update this post as soon as LEGO releases the specifics. Until then, keep an eye out for this exciting GWP.

The US retail price for the 72306 PlayStation set is $179.99. 40899 Astro Bot is the gift with purchase that comes with it: it isn't sold separately, so it has no price of its own. Neither is available at an official Indian retailer such as Toycra or MyBrickHouse, and no India MRP has been announced.

This GWP is a strong contender for one of the best free sets of 2026, especially for gamers. The build itself promises to be engaging, and the final model is sure to be a conversation starter on any display shelf. While we don’t have concrete details on Indian availability or pricing yet, the Astro Bot is definitely one to watch.

Keep building, keep dreaming... and don't let your wallet see your LEGO wishlist.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version applied an import formula to the 72306 PlayStation set's US price and presented the result (₹22,200) as 40899's import price. 40899 is a gift with purchase with no retail price; the figure is removed.

On that bombshell, bubyee.$boi_t$
 WHERE slug = 'lego-40899-astro-bot-gwp-officially-unveiled-arrives-october' AND md5(content) = '089c4a9b7ab1edc9b2da57d69190b61d';

-- lego-ministry-munchies-the-daily-prophet-stands-40901-compan
UPDATE public.reviews SET content = $boi_t$Your wallet is already bracing for the LEGO Ministry of Magic Collectors' Edition, and now this companion set drops. [40901](/sets/40901-ministry-munchies-the-daily-prophet-stands) Ministry Munchies & The Daily Prophet Stands is a gift-with-purchase, meaning it's not something you can just buy outright unless you're willing to brave the grey market. It's designed to flesh out that massive Ministry set, but does it stand on its own? Let's dive in.

This set includes 152 pieces and two minifigures: Cornelius Fudge and a Daily Prophet Vendor. Fudge, the Minister for Magic himself, is a welcome inclusion. He’s sporting a striped suit and bowler hat, using a headpiece that originally appeared for Captain Picard. It works well here, giving him that slightly stuffy, official look. The Daily Prophet Vendor is also a neat addition, with a torso and dual-moulded arms that have seen previous use, and a new headpiece. The only minor quibble? Ideally, the newspaper stand would have some actual Daily Prophet branding, but this is a decent stand-in.

The core of the set is the Ministry’s atrium. The movie version is a busy place, and the main Ministry set ([76476](/sets/76476-the-ministry-of-magic-collectors-edition)) has been criticised for feeling a bit empty. This GWP aims to fix that. You get a Daily Prophet stand, complete with stickered headlines and printed newspapers. Then there's the Ministry Munchies stall, a small background element from the films, with a roof shape and globe that are accurate. Finally, there’s the second part of the Fountain of Magical Brethren. In the films, it’s split into two statues. The main set has one, and this GWP provides the other, featuring a witch. It’s a nice build, with new pearl gold hair element. However, the film version also includes a centaur and a goblin, which are conspicuously absent here.

This is where the set’s main problem lies. The review article itself states it repeatedly: these elements should have been in the main Ministry set from the start. Cornelius Fudge? In the big set. The complete fountain? In the big set. The stalls? Also better suited to the main build. As a GWP, it feels like LEGO is nickelling and diming fans, splitting up content that really belongs together.

Individually, the builds are fine. The fountain statue is quite good, and the stalls add a bit of life. But the minifigures are the real draw, especially Fudge. If you’re buying the big Ministry set anyway, this GWP is a no-brainer to add some detail. But if you were hoping for a standalone Harry Potter set that’s a great build on its own, this isn't it. It’s a collection of accessories and a partial statue that feels more like an afterthought than a complete package. It's a shame because the potential for something truly special was there.

40901 is a gift with purchase: it isn't sold separately, so it has no retail price. For now it's only available free with a qualifying LEGO order; MyBrickHouse and Toycra are the stores to watch if that ever changes.

The verdict is clear: if you're dropping the cash on the massive Ministry of Magic set, this GWP will complement it nicely. But don't go out of your way to hunt this down unless you're a hardcore Harry Potter completist. It’s a companion piece, and it functions best as one.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version gave 40901 a US price of $130 "if it were sold separately" and an estimated import price of ₹16,850, and its WAIT verdict said "the price will drop". 40901 is a gift with purchase that isn't sold separately, so the figures are removed and the verdict is now IMPORT ONLY.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.$boi_t$, verdict = $boi_t$IMPORT ONLY$boi_t$, updated_at = now()
 WHERE slug = 'lego-ministry-munchies-the-daily-prophet-stands-40901-compan' AND md5(content) = 'be1e89791e4da035b18e33b800405bc8';

-- late-august-2026-lego-gwps-grond-steering-wheel-and-botanica
UPDATE public.news_articles SET content = $boi_t$Your August LEGO haul just got a little more interesting, and your wallet might be preparing for impact. LEGO is rolling out a fresh wave of Gift With Purchase (GWP) promotions starting late August 2026, bringing back some popular items and introducing bundle deals. It’s the perfect time to snag those sets you’ve been eyeing, especially with the Back to Hogwarts campaign looming.

For our Australian and New Zealand readers, the sought-after [40893](/sets/40893-grond) Grond GWP is making a comeback. This time, it’s free with the purchase of the [11377](/sets/11377-the-lord-of-the-rings-minas-tirith) Minas Tirith set. Over in the UK and Europe, fans can get their hands on the [5009005](/sets/5009005-entrance-gate) Entrance Gate GWP, a companion piece to the soon-to-retire [21353](/sets/21353-the-botanical-garden) The Botanical Garden. North America isn't left out either, with the [40894](/sets/40894-koenigsegg-sadairs-spear-steering-wheel) Koenigsegg Sadair’s Spear Steering Wheel GWP returning, bundled with the [42232](/sets/42232-koenigsegg-sadairs-spear-megacar) Koenigsegg Sadair’s Spear Megacar.

Beyond these specific set promotions, there are also general spend-based GWPs. Globally, you can get a [30730](/sets/30730-trainer-supplies) Trainer Supplies polybag when you spend US$40 (or local equivalent) on a range of themes including One Piece, City, and NINJAGO. Another global offer sees the [30733](/sets/30733-badnik-skorp) Badnik: Skorp polybag free with a US$40 spend on themes like Sonic the Hedgehog, Super Mario, and Minecraft.

Australian fans get an extra perk: spending AU$325 or more on LEGO.com can net you the [40913](/sets/40913-vintage-parade-car) Icons Vintage Parade Car GWP, but you’ll need to use exclusive promo codes, which are quite limited. These codes stack with other offers, meaning you could potentially grab both Grond and the Vintage Parade Car if you’re strategic.

LEGO is also running bundle deals from August 21-29, offering 25% off the second set when you buy a qualifying pair. This includes discounts on sets like the Iron Man MK4 Bust and Iron Spider-Man Bust, Jango Fett Helmet and AT-AT Driver Helmet, and even some floral and WALL-E sets. These discounts are modest, but could be worthwhile if you were planning on picking up both items in a bundle anyway.

No official LEGO India pricing has been confirmed for these GWPs, since LEGO doesn't sell them separately. Two are listed on their own by an Indian store: MyBrickHouse has the 40894 Koenigsegg Sadair’s Spear Steering Wheel at ₹2,499 (in stock as of 29 Sep 2026) and 40893 Grond at ₹2,999 (out of stock as of 29 Sep 2026). Keep an eye on MyBrickHouse and Toycra for the others, though these are often limited to specific regions.

These promotions run until August 28th in most regions, with the UK/EU Botanical Garden offer lasting until October 1st. It's a good opportunity to top up your collection before the big LEGO Harry Potter event kicks off on August 29th.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version estimated a ₹5,500 import price for 40894. MyBrickHouse lists it at ₹2,499; the estimate is replaced with the listing.

Verdict: WAIT — check prices at MyBrickHouse and Toycra before pulling the trigger.$boi_t$
 WHERE slug = 'late-august-2026-lego-gwps-grond-steering-wheel-and-botanica' AND md5(content) = '9071f7c4f25001e4a21888979dd109a9';

-- lego-40902-tribute-to-leonardo-da-vinci-gwp-news-what-it-mea
UPDATE public.news_articles SET content = $boi_t$Your wallet just ran a marathon; the LEGO Tribute to Leonardo da Vinci GWP hides behind a $150 spend threshold. The 251‑piece set is the latest freebie in LEGO’s historical tribute series, and it arrives only if you shell out enough cash on the official LEGO.com store. It’s not a standalone product you can add to a cart; it’s a gift with purchase, free when you spend over £135, $150 or €150.

The set builds a slice of da Vinci’s workshop, complete with a colourful mosaic floor that looks like a tiny fresco. Three printed tiles and a single sticker bring the scene to life. Inside the workshop you’ll find an easel holding the Mona Lisa, a desk cluttered with an ink pot, quill, mirror and a printed tile of his ornithopter plans. A pear rests on a side table – a nod to his botanical sketches – while a cat perches on the balcony, reminding fans of his feline studies. The minifigure of the Renaissance polymath sports a white beard, blue tunic and a back bracket that can hold the flying machine.

All the parts are solidly LEGO‑bricked, and the level of detail is surprisingly high for a GWP. The set also includes a tiny mirror tile that hints at da Vinci’s habit of writing in reverse, a clever little Easter egg for history buffs. The only sticker is for a mirror on the desk; the rest of the build relies on printed elements and clever moulding.

Because it’s a gift‑with‑purchase, the set won’t appear in any Indian retailer catalog. Indian fans will have to order directly from LEGO.com, meet the spend requirement, and hope the shipment reaches India in time for their next build session. Expect a typical 4–6 week lag from the global launch, and keep an eye on both MyBrickHouse and Toycra for any future listings.

40902 is a gift with purchase, so LEGO doesn't sell it separately. MyBrickHouse has listed it on its own at ₹2,499, but it was out of stock when we last saw the listing on 22 Sep 2026.

Given the lack of a direct purchase route and the need to spend a serious amount just to qualify, the safest move for Indian builders is to wait for a more accessible channel. Keep building, keep dreaming... And don't let your wallet see your LEGO wishlist.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹19,200. 40902 is a gift with purchase; the estimate is replaced with MyBrickHouse's last listing (₹2,499, out of stock, 22 Sep 2026).

On that bombshell, bubyee.$boi_t$
 WHERE slug = 'lego-40902-tribute-to-leonardo-da-vinci-gwp-news-what-it-mea' AND md5(content) = '77e13381c10dd46403473ff10a41f3ba';

-- lego-40902-tribute-to-leonardo-da-vinci-gwp-worth
UPDATE public.news_articles SET content = $boi_t$Your wallet just whispered, “Did you really need another da Vinci?” The June 2026 Double Insiders Points promo is in full swing, and LEGO is dangling a free Leonardo da Vinci GWP if you splash US$150 on LEGO.com. Free sounds free, until you factor in the points you’re chasing, the shipping, and the inevitable “what‑if” about the set’s real value.

First off, the set itself is a tidy nod to the Renaissance polymath. The minifigure isn’t brand‑new – it recycles the head, torso and legs from the [10363](/sets/10363-leonardo-da-vincis-flying-machine) Flying Machine – but the cap replaces his signature white hair, giving him a fresh silhouette. The biggest surprise is the printed elements. Where most GWPs still rely on stickers, LEGO has printed the mirror, the Mona Lisa tile, and even a tiny green pear. Printed tiles are a quiet win; they eliminate the hassle of peeling stickers and signal a shift toward higher‑quality GWP builds.

The build is modest, echoing the template of the Tribute to Galileo Galilei ([40595](/sets/40595-tribute-to-galileo-galilei)). A small workshop scene, a shelf of paints, a geode, a crystal, and a curious kitten perched by a window. The centerpiece is a tiny oyster, a quirky nod to one of Leonardo’s many musings about the sea. The scene feels like a miniature study, complete with a sketch of his Ornithopter, a quill, and a mirror that hints at his fascination with mirror writing. The printed Mona Lisa tile is the real show‑stopper – a tiny homage that would look out of place on a sticker‑only set.

What’s missing? Only one sticker – a shiny reflective circle for the mirror. Everything else is printed, which is a relief for those who’ve wrestled with misaligned stickers on past GWPs. The set’s parts count is low, making it a quick build that still feels rewarding thanks to the printed details. It’s a good fit for collectors who already own the Flying Machine minifigure and want a richer display piece without the sticker drama.

The promotional angle is clever. Double points on all purchases from 19‑29 June means you can stack points on the $150 spend, then snag the GWP for “free.” In practice, you’re still spending a decent chunk on LEGO.com, and the GWP’s value is essentially baked into that spend. For fans who were already planning a big order, the da Vinci GWP is a nice bonus. For those on a tighter budget, the extra spend might feel like a forced upsell.

Overall, the 40902 GWP is a tidy, well‑printed homage to Leonardo. It doesn’t break new ground in terms of shape or scale, but the printed details elevate it above the usual sticker‑laden freebies. If you’re already hitting the $150 threshold, grab it. If not, consider whether the points and extra spend are worth the modest display piece.

No Indian store prices yet. Based on the US retail price of $— (price not disclosed) and current exchange rates, expect this to land somewhere around ₹— estimated import price — not confirmed India retail. That is roughly 18 months of Netflix Premium. MyBrickHouse and Toycra are the stores to watch — Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra. Expect a 4–6 week lag from global launch.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait

Corrected 29 Sep 2026: the headline showed a broken price placeholder ("Worth ₹—?"). A gift with purchase has no price, so the headline now asks whether it's worth chasing.

Standard disclaimer: if money means nothing to you, ignore everything above and just buy it. The rest of us will be here, doing the maths on EMI options..$boi_t$, title = $boi_t$LEGO 40902 Tribute to Leonardo da Vinci (GWP): Worth Chasing?$boi_t$, seo_title = $boi_t$LEGO 40902 Tribute to Leonardo da Vinci (GWP): Worth Chasing?$boi_t$
 WHERE slug = 'lego-40902-tribute-to-leonardo-da-vinci-gwp-worth' AND md5(content) = 'cd8c222c7fe3ba229e90ec96ae02c683';

-- lego-40912-sea-serpent-gift-with-purchase-revealed
UPDATE public.news_articles SET content = $boi_t$Brickset has revealed the LEGO [40912](/sets/40912-sea-serpent) Sea Serpent, a gift-with-purchase set based on the classic [6057](/sets/6057-sea-serpent) Sea Serpent from 1992. This nostalgic build is the winner of the 'A Twist of Nostalgia' Ideas competition, bringing a piece of the past back to our shelves. It's set to launch on LEGO.com starting July 7th.

However, the exact spending threshold required to snag this freebie remains unconfirmed. This is a common frustration for fans who love these smaller, themed sets but often find the qualifying purchase amount out of reach. Many commenters express a desire to simply purchase these sets outright, rather than be forced into buying other, potentially less desired, items just to get the GWP. The original 1992 set came with five minifigures, and some fans feel the new version falls short in that regard, along with other proportion and accessory details.

Despite some criticisms regarding minifigure count and stylistic differences from the original, the new sail and shield elements are receiving praise. The inclusion of brown elements and clever SNOT (Studs Not On Top) techniques for the castle turret pieces are also noted positively. For those who missed out on the original or long for that castle theme nostalgia, this set holds significant appeal. The challenge, as always with GWPs, will be meeting the spending requirement without feeling like you're overpaying for unwanted bricks. Given the GWP nature and no confirmed set price, this is unlikely to be available through standard Indian retail channels.

40912 is a gift with purchase, so LEGO doesn't sell it separately. In India, though, MyBrickHouse lists it on its own at ₹2,499 (in stock as of 29 Sep 2026).

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version estimated an import price of ₹2,700–₹3,800 from the price of "comparable sets", with an IMPORT ONLY verdict ("not in Indian stores"). MyBrickHouse lists 40912 at ₹2,499, so the estimate is replaced with the listing and the verdict is now WAIT, as in our review of the set.

Verdict: WAIT.$boi_t$
 WHERE slug = 'lego-40912-sea-serpent-gift-with-purchase-revealed' AND md5(content) = '1de8c0af6bb51873bfcad810c8979974';

-- lego-koenigsegg-sadairs-spear-steering-wheel-40894-gwp-funct
UPDATE public.news_articles SET content = $boi_t$Your wallet is safe, for now. LEGO’s latest gift-with-purchase, the [40894](/sets/40894-koenigsegg-sadairs-spear-steering-wheel) Koenigsegg Sadair's Spear Steering Wheel, is a Technic piece that might just make you question what a GWP should even be. This isn't your typical brick-built car or a miniature spaceship. It's a steering wheel. Yes, a steering wheel.

The set, which comes with 228 pieces, is a freebie when you buy the [42232](/sets/42232-koenigsegg-sadairs-spear-megacar) Koenigsegg Sadair's Spear Megacar. The review over at Brickset highlights a rather clever bit of engineering packed into this unusual promotional item. The real car’s steering wheel has a unique feature where the instrument cluster stays vertical even as the wheel turns. LEGO’s model replicates this, along with functioning paddle-shift gear selectors. There are five stickers, but thankfully, only one is essential. The rest are for carbon fibre detailing on the base, which the reviewer skipped entirely. A separate dial shows the selected gear, which rotates when the paddle shifters are used. It’s a surprisingly intricate mechanism for a GWP, employing a new spring-loaded 9-tooth cog to drive the indicator.

Technic GWPs are rare beasts, and this one is only available until July 7th on LEGO.com. While the functionality is impressive, some commenters on the original review expressed lukewarm feelings. One user pointed out that while the functionality is neat, the visual appeal is lacking, making it a display piece they wouldn't buy separately. Another noted that the main car might be discounted later, making this GWP feel like a pricey bonus if you're not already sold on the Megacar.

The steering wheel is a gift with purchase that comes with the 42232 Koenigsegg Sadair's Spear (US$239.99), so LEGO doesn't sell it on its own. In India, MyBrickHouse lists it separately at ₹2,499 (in stock as of 29 Sep 2026). MyBrickHouse and Toycra are also the stores to watch for the main 42232 set.

While the engineering is commendable and it’s a cool concept for a Technic GWP, the question remains: is a steering wheel enough to sway you? If you’re already planning to buy the Koenigsegg Megacar, then sure, grab it while you can. For everyone else, this is probably a pass. The functionality is interesting, but the display value seems questionable for a standalone purchase.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version estimated that 40894 "would cost around ₹28,800 if sold separately", based on the main car's price. MyBrickHouse sells it at ₹2,499; the estimate is replaced with the listing.

Verdict: WAIT. Good set, but the price will drop.$boi_t$
 WHERE slug = 'lego-koenigsegg-sadairs-spear-steering-wheel-40894-gwp-funct' AND md5(content) = '9d65f2cf9c9d1f804e97ad62440d4dab';

-- lego-xfiles-scullys-lab-40896-gwp-review-is-it-worth-the-cha
UPDATE public.news_articles SET content = $boi_t$Your wallet just sent an SOS after hearing about the LEGO X‑Files lab GWP. The promise of a free 221‑piece Scully’s Lab sounds tempting, but the catch is that you have to buy the main 21369 set first – £179.99 or $199.99 at LEGO.com. Let’s unpack whether the extra lab is a clever add‑on or just a nice‑to‑have extra.

The lab sits on a 16 × 18 baseplate and feels surprisingly solid for its size. The build includes a worktop with a sink, a row of cupboards built from four 3 × 4 window frames, and a central autopsy table lit from above. The detailing is where the set shines: a sunken sink, a microscope on a desk, and a tiny fly tile on the floor give the lab a lived‑in vibe. The minifigure of Dana Scully sports a white lab coat over light‑blue scrubs, latex gloves, and protective glasses that tilt to one side, giving her a worried look. The only glaring omission is the alien minifigure you’d expect on the dissection table – you have to buy the larger X‑Files set to get one.

The set’s piece count of 221 puts it in the mid‑range for GWP builds. It’s not a standalone experience; it truly shines when paired with the main set, completing the investigative scene. If you’re already planning to buy the 21369 X‑Files, the lab feels like a well‑crafted bonus rather than a must‑have. On its own, the lack of an alien makes the build feel a touch incomplete, but the construction techniques are solid and the minifigure is a nice addition to any FBI‑themed collection.

Overall, the lab is an excellent accompaniment that rewards the buyer of the main set. It’s not essential, but if you’re a fan of the series and enjoy adding depth to your builds, it’s worth the extra effort – provided you’re comfortable with the price of the main set.

Scully's Lab is a gift with purchase from LEGO, but in India MyBrickHouse sells it on its own at ₹1,999 (in stock as of 29 Sep 2026).

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹25,600, with an IMPORT ONLY verdict ("not in Indian stores"). MyBrickHouse sells 40896 at ₹1,999, so the estimate is replaced with the listing and the verdict is now WAIT, as in our review of the set.

Verdict: WAIT.$boi_t$
 WHERE slug = 'lego-xfiles-scullys-lab-40896-gwp-review-is-it-worth-the-cha' AND md5(content) = 'df220e542df8f5c4bae53d24f34726a0';

-- lego-tribute-to-leonardo-da-vinci-40902-worth-19600
UPDATE public.reviews SET content = $boi_t$Your wallet just got a reality check – a gift‑with‑purchase that hides behind a US$150 spend. A tribute to Leonardo da Vinci sounds classy, but the spend it takes to get one feels more like a down‑payment on a small car.

The [40902](/sets/40902-tribute-to-leonardo-da-vinci) Tribute to Leonardo da Vinci arrives as a Gift with Purchase (GwP), meaning you only get it when you spend a certain amount on LEGO’s online store. It isn’t a standalone launch you can snag from a local retailer, and that already puts it in a niche corner of the market. The set itself is modest: 251 pieces, a small bust of the master, a tiny easel, and a few iconic inventions like the flying machine and the Vitruvian Man. Build time hovers around an hour for most builders, which is perfect for a quick weekend session.

From a construction standpoint, the set uses a lot of classic bricks and plates, with a few specialty elements for the inventions. The techniques are straightforward – a lot of brick‑on‑brick stacking, a few snot (stud‑not‑on‑top) tricks for the flying machine’s wings, and a modest amount of internal support. If you enjoy the calm of a low‑piece count build, this will feel satisfying. If you crave the drama of large‑scale builds with intricate mechanisms, you’ll probably yawn halfway through.

Design-wise, LEGO does a decent job of capturing Leonardo’s silhouette. The bust is recognisable, and the easel adds a nice visual anchor. The included inventions are more symbolic than functional; the flying machine’s wings don’t actually move, and the Vitruvian Man is a static figure. For a collector who loves the Renaissance theme, the set hits the sweet spot. For a fan who expects moving parts or a more elaborate diorama, the set feels a bit under‑delivered.

Value is hard to judge the usual way: a gift with purchase has no price of its own, so there's no per-piece cost to compare. The specialty elements are few, so the spend it takes to unlock it isn't justified by an abundance of unique parts. Here, the appeal is purely the brand‑name tribute and the exclusivity of a GwP.

Community reaction is mixed. Some LEGO fans appreciate the homage to a historical figure and see the set as a nice addition to a Renaissance‑themed collection. Others criticize the high threshold and the lack of a functional build, calling it a “collector’s token” rather than a true building experience. The double loyalty points promotion for Insiders adds a tiny incentive, but it doesn’t offset the core issue: you have to spend a lot to get a modest set.

If you’re already planning a big cart on LEGO’s website, grabbing this set could be a decent side‑kick – especially if you love Leonardo’s legacy and enjoy displaying mini‑figures on a shelf. But for most builders, the price‑to‑experience ratio leans toward “skip it and buy a regular set.”

40902 is a gift with purchase, so LEGO doesn't sell it separately. MyBrickHouse has listed it on its own at ₹2,499, but it was out of stock when we last saw the listing on 22 Sep 2026.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Corrected 29 Sep 2026: an earlier version called 40902 "a $150 gift‑with‑purchase" (US$150 is the spend needed to get it), gave it 1,200 pieces (the catalogue has 251), worked out a per-piece price from those figures, and estimated an import price of ₹19,600, which also appeared in the headline. The figures are corrected or removed; MyBrickHouse's last listing was ₹2,499 (out of stock, 22 Sep 2026).

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.$boi_t$, title = $boi_t$LEGO Tribute to Leonardo da Vinci (40902): Worth Chasing?$boi_t$, seo_title = $boi_t$LEGO Tribute to Leonardo da Vinci (40902): Worth Chasing?$boi_t$, excerpt = $boi_t$Your wallet just got a reality check – a gift‑with‑purchase that hides behind a US$150 spend. A tribute to Leonardo da Vinci sounds classy, but the spend…$boi_t$, seo_description = $boi_t$Your wallet just got a reality check – a gift‑with‑purchase that hides behind a US$150 spend. A tribute to Leonardo da Vinci sounds classy, but the spend…$boi_t$, updated_at = now()
 WHERE slug = 'lego-tribute-to-leonardo-da-vinci-40902-worth-19600' AND md5(content) = 'f0e2b6f2f2240e9398f782f679708cd9';

-- lego-darth-vaders-lightsaber-40897-worth-the-import-price
UPDATE public.reviews SET content = $boi_t$Just 174 pieces, but the pain of wanting something you can't easily get is universal. LEGO has dropped another life-size prop replica with [40897](/sets/40897-darth-vaders-lightsaber) Darth Vader's Lightsaber, and if you're a Star Wars fan with a penchant for display pieces, your wallet is already bracing for impact. The problem? It's not officially coming to India.

This isn't just any lightsaber; it's the lightsaber. The one that defined a generation of villainy. While the source material might show minor variations across films, this model leans towards the Obi-Wan Kenobi series version, with a slightly shorter grip and distinct activator details. It’s instantly recognisable, and LEGO’s execution here is, dare I say, superb. The proportions feel right, and it’s sturdy enough to handle without fear of it falling apart. If you've collected the other life-size sabers, like [40917](/sets/40917-the-darksaber) The Darksaber or [40730](/sets/40730-luke-skywalkers-lightsaber) Luke Skywalker's Lightsaber, this will fit right in.

The build focuses on 4x4 round elements, forming the core of the hilt. LEGO has done a commendable job with the details. The emitter shroud, using those curved Technic panels, is a neat trick that replicates the on-screen prop's shape almost perfectly. Even the activator dial has deliberately exposed studs to mimic the original prop's texture. A nice touch is the inclusion of two trans-red 2x2 round bricks representing the kyber crystals, a nod to the lore that Vader's lightsaber houses two. The display stand is simple but effective, allowing the saber to be displayed in either direction and featuring the standard printed plaque.

Now, for the nitpicks. On screen, Vader's lightsaber has six or seven black handgrips; this model has eight. I can see it being a compromise for a smoother look, but it's still a deviation from the prop.

The biggest frustration, however, is its availability. This set is positioned as a gift-with-purchase for the rather colossal [75457](/sets/75457-executor-super-star-destroyer) Executor Super Star Destroyer. That's a massive spend threshold. And even then, it's only available in select markets. This "limited availability" is a common LEGO tactic that leaves many fans feeling left out, especially those outside the primary markets.

It isn't sold on its own: Brickset lists it as a gift with purchase with 75457 at LEGO.com in October 2026, so there's no retail price to convert into rupees. No Indian stores like Toycra or MyBrickHouse have it listed, and it's unlikely they will unless LEGO India decides to officially release it here. Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission). For now, it's import only.

This set is a fantastic display piece for any Star Wars fan. The build is solid, the design is accurate save for a minor grip count quibble, and it fits perfectly into the growing collection of lightsaber replicas. If you can get your hands on it without breaking the bank through unofficial channels, it's definitely worth it. But for us in India, the price and the hassle of importing make it a tough proposition.

On that bombshell, it's time to say goodbye. I'll see you on the next one. Bubyee.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: the headline asked whether 40897 was "worth the import price", but it is a gift with purchase that has no price, and the summary still quoted the opening corrected on 27 Sep. Both are updated.

Updated 27 Sep 2026: opening corrected. It began with another set's specs ("ten thousand pieces, five feet tall") before admitting that wasn't this set; 40897 has 174 pieces (Brickset). Also corrected 27 Sep 2026: removed a stray "BUY NOW" line that contradicted the IMPORT ONLY verdict; restated the handgrip nitpick in our own voice (it had narrated an unnamed reviewer, and a claim about the 2021 Luke Skywalker lightsaber that rested on that reviewer was removed); removed an unsourced "US retail price $99.99" and its rupee conversion, because Brickset lists 40897 as a LEGO.com gift with purchase with no retail price.$boi_t$, title = $boi_t$LEGO Darth Vader's Lightsaber (40897): Worth Chasing?$boi_t$, seo_title = $boi_t$LEGO Darth Vader's Lightsaber (40897): Worth Chasing?$boi_t$, excerpt = $boi_t$Just 174 pieces, but the pain of wanting something you can't easily get is universal. LEGO has dropped another life-size prop replica with 40897 Darth…$boi_t$, seo_description = $boi_t$Just 174 pieces, but the pain of wanting something you can't easily get is universal. LEGO has dropped another life-size prop replica with 40897 Darth…$boi_t$, updated_at = now()
 WHERE slug = 'lego-darth-vaders-lightsaber-40897-worth-the-import-price' AND md5(content) = 'daeb69a84dab600de2692129669c9f35';
