-- boi:issue 422
-- boi:backup-tables public.news_articles
-- boi:expect-before select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','46ef10bff0c0bfdfed0abdd59ca409e6'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','24ea8e0361202d74da7cc666f86f1d73')) = 2
-- boi:expect-after select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','d1bd6685403516e1b0b9eb418250f5ea'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','8bd29ec2c33b53c8a58b0620d73ba6c8')) = 2
-- P12 follow-up (Abhinav, 30 Sep 2026): the 29 Sep correction notes on the two surviving 40900 articles
-- (C = lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w, B = lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit)
-- quoted the removed estimates (₹3,400 / $24.99 on C, ₹2,700 / $19.99 on B). G16: the note stays, keeps its date, and now
-- says "an earlier version included an unverified price estimate, which has been removed" with no price figure.
-- Only the note sentence changes: replace() of the exact old note, guarded by each row's md5 (expect-before).
-- Applies in the next batch with #412 and #435.
UPDATE public.news_articles SET content = replace(content, $boi_old$Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹3,400, calculated from a US retail price of $24.99. 40900 is a gift with purchase and has no retail price, so those figures are removed. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$boi_old$, $boi_new$Corrected 29 Sep 2026: an earlier version included an unverified price estimate, which has been removed. 40900 is a gift with purchase and has no retail price. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$boi_new$)
  WHERE slug = 'lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w' AND md5(content) = '46ef10bff0c0bfdfed0abdd59ca409e6';
UPDATE public.news_articles SET content = replace(content, $boi_old$Corrected 29 Sep 2026: this article said there were no official details on 40900's release, theme or price, and estimated an import price of ₹2,700 from a US price of $19.99. LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately; the claim and the price are removed, and a stray second verdict line is deleted.$boi_old$, $boi_new$Corrected 29 Sep 2026: an earlier version included an unverified price estimate, which has been removed. It also said there were no official details on 40900's release, theme or price; LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately, so that claim is removed too, and a stray second verdict line is deleted.$boi_new$)
  WHERE slug = 'lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit' AND md5(content) = '24ea8e0361202d74da7cc666f86f1d73';
