-- boi:issue 422
-- boi:backup-tables public.news_articles
-- boi:expect-before select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-40900-scary-haunted-tree-gwp-revealed-halloween-2026','2842ed675abc4f4912aa89cb037c9bab'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','95c84eb47e7c84ff7c36dadc51153c09'), ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','e7c2fe39670da0977cbebe0ff5cc1911')) = 3
-- boi:expect-after select (select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','24ea8e0361202d74da7cc666f86f1d73'), ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','46ef10bff0c0bfdfed0abdd59ca409e6'))) + (select count(*) from public.news_articles where slug = 'lego-40900-scary-haunted-tree-gwp-revealed-halloween-2026') * 10 = 2
-- #422 / P10 item 3 (G16): 40900 Scary Haunted Tree. A (lego-40900-scary-haunted-tree-gwp-revealed-halloween-2026, 22 Sep) and C (lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w, 28 Sep) are
-- true duplicates of the same reveal; C survives (the accurate one: LEGO's button-lit mouth, dimensions, age,
-- Creator theme) and A's one correct extra (the 40772 / 40697 lineage) moves into it. A's URL 308s to C
-- (next.config.mjs, shipped in a site deploy BEFORE this runs), then A's row is removed -- the one removal
-- G16 allows, a merged true duplicate; its full row is in boi_backups and in
-- boi-db-backups/2026-09-29-422-40900/news_articles_40900_backup.json. B (lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit) is a distinct angle and stays,
-- corrected. Every survivor: invented prices removed, "gift with purchase, not sold separately" stated, one
-- verdict (IMPORT ONLY) on both. Generated by boi-db-backups/2026-09-29-422-40900/build_422.py.
UPDATE public.news_articles SET content = $boi_t$LEGO.com has just unveiled a new seasonal gift-with-purchase, the [40900](/sets/40900-scary-haunted-tree) Scary Haunted Tree, and it’s looking appropriately spooky. This 218-piece Creator set promises to add some Halloween flair to your collection, featuring a black tree with posable arms and a mouth that lights up when you press a button. It also comes with a small pumpkin and a crow build, making it a nice little diorama piece for the spooky season.

The set is designed for builders aged 8 and up, and the press release highlights its potential as both a fun building activity and a decorative item. The tree itself stands over 6 inches tall, 3 inches long, and 7 inches wide, offering a decent display presence for its implied size as a GWP. The light-up feature adds a nice interactive element, perfect for creating eerie scenes or just spooky ambient lighting for your desk.

LEGO hasn't confirmed the dates or the qualifying spend. Reports put the threshold at around US$100 / £90 / €100 on LEGO.com and the start at 21 September. It follows two earlier Halloween gifts with purchase that also lit up: [40772](/sets/40772-celebration-series-luminous-ghost) Luminous Ghost (2025) and [40697](/sets/40697-halloween-pumpkin) Halloween Pumpkin (2024).

The comments section on Brickset shows a mix of reactions, with some users finding it "very cute" and comparing it to previous seasonal GWPs like last year's ghost set. Others are already making humorous comparisons to pop culture characters. The consensus is that it’s a charming addition for Halloween fans, especially with the light-up function.

40900 is a gift with purchase: it isn't sold separately, so it has no retail price in India or anywhere else. It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100). No Indian retailer has announced it.

If you want one, the official route is a qualifying LEGO order during the promotion. Outside it, the only option is the secondary market.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹3,400, calculated from a US retail price of $24.99. 40900 is a gift with purchase and has no retail price, so those figures are removed. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.

On that bombshell, bubyee.$boi_t$
 WHERE slug = 'lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w' AND md5(content) = 'e7c2fe39670da0977cbebe0ff5cc1911';

UPDATE public.news_articles SET content = $boi_t$This week's LEGO set popularity charts have thrown a curveball, and it's not a giant, soulless space station or a ridiculously oversized vehicle. No, the surprise standout is the LEGO [40900](/sets/40900-scary-haunted-tree) Scary Haunted Tree, a set that has apparently captured the imagination of builders everywhere this past week. While the usual suspects like the Burj Khalifa and some older fan-favourites popped up, it's this spooky little tree that's earned a spot in the top viewed sets on Brickset.

The list, compiled from set detail page views, shows the Scary Haunted Tree climbing the ranks. It's a curious phenomenon, especially for a set that isn't part of a major ongoing theme or a highly anticipated new release. The other sets making waves include the Burj Khalifa ([21055](/sets/21055-burj-khalifa)), Aquabase Invasion ([7775](/sets/7775-aquabase-invasion)), Yoda Bust ([75255](/sets/75255-yoda)), Black Knight's Castle ([6086](/sets/6086-black-knights-castle)), and the Lion Knights' Castle ([10305](/sets/10305-lion-knights-castle)). It’s interesting to see older sets like Aquabase Invasion and even the rather obscure [75201](/sets/75201-first-order-at-st) First Order AT-ST resurfacing in the top viewed. Some fans on Reddit are speculating that these older sets are appearing due to discussions on forums about "worst sets ever" or nostalgic deep dives, which makes a certain kind of sense.

The likely reason is simple: the week before, LEGO revealed 40900 as its Halloween gift with purchase, a 218-piece Creator build with a light-up mouth, a crow and a pumpkin (see our report: [LEGO Creator 40900 Scary Haunted Tree revealed](/news/lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w)).

As a gift with purchase, 40900 isn't sold separately, so no Indian retailer lists it.

40900 is a gift with purchase: it isn't sold separately, so it has no retail price in India or anywhere else. It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100). No Indian retailer has announced it.

Outside the promotion, the only way to get one is the secondary market, or a qualifying LEGO order while travelling abroad.

Verdict: IMPORT ONLY. Not in Indian stores — grey market or wait.

Corrected 29 Sep 2026: this article said there were no official details on 40900's release, theme or price, and estimated an import price of ₹2,700 from a US price of $19.99. LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately; the claim and the price are removed, and a stray second verdict line is deleted.

On that bombshell, bubyee.$boi_t$,
  seo_description = 'The Scary Haunted Tree topped this week''s most-viewed LEGO sets on Brickset -- a gift with purchase that isn''t sold separately.'
 WHERE slug = 'lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit' AND md5(content) = '95c84eb47e7c84ff7c36dadc51153c09';

DELETE FROM public.news_articles
 WHERE slug = 'lego-40900-scary-haunted-tree-gwp-revealed-halloween-2026' AND md5(content) = '2842ed675abc4f4912aa89cb037c9bab';
