-- boi:issue 422
-- boi:backup-tables public.news_articles
-- boi:expect-before select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','46ef10bff0c0bfdfed0abdd59ca409e6'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','24ea8e0361202d74da7cc666f86f1d73')) = 2
-- boi:expect-after select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','4598e86e3a3b7a53891f309a4a9d35b4'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','c30d840c43bf404ce6736ec9ea413bc9')) = 2
-- P12 follow-up (Abhinav, 30 Sep 2026), the two surviving 40900 articles (C = ...-revealed-as-new-gift-w, B = ...-is-this-weeks-surprise-hit):
--  1. Qualifying spend: the US$100 / £90 / €100 figure came only from a Stonewars rumour (via Jay's Brick Blog); LEGO (Brickset 134769)
--     says thresholds are not yet known. Now "a qualifying spend (not yet confirmed by LEGO)", no figure.
--  2. Dates: Brickset's set data (brickset.com/sets/40900-1, Launch/exit 21 Sep 26 - 30 Sep 26) now covers them:
--     C: "Brickset lists the promotion as running 21-30 September 2026." No Stonewars attribution.
--  3. Promotion wording in both articles is past tense ("ran 21-30 September 2026"); the window has closed.
--  4. Correction notes: no price figure; "Corrected 29 Sep 2026, updated 30 Sep 2026" and mention the date/tense update (G16).
--  Kept: the 40772 (2025) / 40697 (2024) light-up GWP lineage -- Brickset tags both Gift with Purchase + Halloween + Light Brick.
-- Each change is a replace() of an exact sentence, guarded by the row's md5 (expect-before = fix 422's expect-after).
-- Applies in the next batch with #412 and #435.
UPDATE public.news_articles SET content = replace(replace(replace(replace(content, $o0$LEGO hasn't confirmed the dates or the qualifying spend. Reports put the threshold at around US$100 / £90 / €100 on LEGO.com and the start at 21 September.$o0$, $n0$It came with a qualifying spend (not yet confirmed by LEGO). Brickset lists the promotion as running 21–30 September 2026.$n0$), $o1$It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100).$o1$, $n1$It came free with a qualifying spend (not yet confirmed by LEGO) on a LEGO order during the promotion, which ran 21–30 September 2026.$n1$), $o2$If you want one, the official route is a qualifying LEGO order during the promotion. Outside it, the only option is the secondary market.$o2$, $n2$The official route was a qualifying LEGO order during the promotion, which ran 21–30 September 2026. Now that it has ended, the only option is the secondary market.$n2$), $o3$Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹3,400, calculated from a US retail price of $24.99. 40900 is a gift with purchase and has no retail price, so those figures are removed. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$o3$, $n3$Corrected 29 Sep 2026, updated 30 Sep 2026: an earlier version included an unverified price estimate, which has been removed. 40900 is a gift with purchase and has no retail price. The promotion dates now follow Brickset's set data (21–30 September 2026), and the wording is past tense now that the promotion has ended. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$n3$)
  WHERE slug = 'lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w' AND md5(content) = '46ef10bff0c0bfdfed0abdd59ca409e6';
UPDATE public.news_articles SET content = replace(replace(replace(content, $o0$It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100).$o0$, $n0$It came free with a qualifying spend (not yet confirmed by LEGO) on a LEGO order during the promotion, which ran 21–30 September 2026.$n0$), $o1$Outside the promotion, the only way to get one is the secondary market, or a qualifying LEGO order while travelling abroad.$o1$, $n1$The promotion ran 21–30 September 2026. Now that it has ended, the only way to get one is the secondary market.$n1$), $o2$Corrected 29 Sep 2026: this article said there were no official details on 40900's release, theme or price, and estimated an import price of ₹2,700 from a US price of $19.99. LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately; the claim and the price are removed, and a stray second verdict line is deleted.$o2$, $n2$Corrected 29 Sep 2026, updated 30 Sep 2026: an earlier version included an unverified price estimate, which has been removed. It also said there were no official details on 40900's release, theme or price; LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately, so that claim is removed too, and a stray second verdict line is deleted. The promotion dates now follow Brickset's set data (21–30 September 2026), and the wording is past tense now that the promotion has ended.$n2$)
  WHERE slug = 'lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit' AND md5(content) = '24ea8e0361202d74da7cc666f86f1d73';
