-- boi:issue 422
-- boi:backup-tables public.news_articles
-- boi:expect-before select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','46ef10bff0c0bfdfed0abdd59ca409e6'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','24ea8e0361202d74da7cc666f86f1d73')) = 2
-- boi:expect-after select count(*) from public.news_articles where (slug, md5(content)) in (values ('lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w','f670d538c33957eaa853b97d35429875'), ('lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit','c982b17edaec6b0b4176701d18ea2acf')) = 2
-- P12 follow-up (Abhinav, 30 Sep 2026), the two surviving 40900 articles (C = ...-revealed-as-new-gift-w, B = ...-is-this-weeks-surprise-hit):
--  1. Correction notes: no price figure; "an earlier version included an unverified price estimate, which has been removed"; date kept (G16).
--  2. Qualifying spend: the US$100 / £90 / €100 figure came only from a Stonewars rumour (via Jay's Brick Blog); LEGO (Brickset 134769)
--     says thresholds are not yet known. Replaced by "a qualifying spend (not yet confirmed by LEGO)", no figure (option b).
--  3. C's "start at 21 September" came from the same rumour: kept, labelled as reported and unconfirmed, attributed to Jay's Brick Blog citing Stonewars.
--  Kept: the 40772 (2025) / 40697 (2024) light-up GWP lineage -- Brickset tags both Gift with Purchase + Halloween + Light Brick.
-- Each change is a replace() of an exact sentence, guarded by the row's md5 (expect-before = fix 422's expect-after).
-- Applies in the next batch with #412 and #435.
UPDATE public.news_articles SET content = replace(replace(replace(content, $o0$LEGO hasn't confirmed the dates or the qualifying spend. Reports put the threshold at around US$100 / £90 / €100 on LEGO.com and the start at 21 September.$o0$, $n0$It comes with a qualifying spend (not yet confirmed by LEGO). LEGO hasn't confirmed the promotion dates either: Jay's Brick Blog, citing Stonewars, reported a 21 September start, which remains unconfirmed.$n0$), $o1$It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100).$o1$, $n1$It comes free with a qualifying spend (not yet confirmed by LEGO) on a LEGO order while the promotion runs.$n1$), $o2$Corrected 29 Sep 2026: an earlier version gave an estimated import price of ₹3,400, calculated from a US retail price of $24.99. 40900 is a gift with purchase and has no retail price, so those figures are removed. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$o2$, $n2$Corrected 29 Sep 2026: an earlier version included an unverified price estimate, which has been removed. 40900 is a gift with purchase and has no retail price. This page now also carries our 22 Sep report on the same reveal, whose address redirects here.$n2$)
  WHERE slug = 'lego-creator-40900-scary-haunted-tree-revealed-as-new-gift-w' AND md5(content) = '46ef10bff0c0bfdfed0abdd59ca409e6';
UPDATE public.news_articles SET content = replace(replace(content, $o0$It comes free with a qualifying LEGO order while the promotion runs; LEGO hasn't confirmed the qualifying spend (reports put it at around US$100 / £90 / €100).$o0$, $n0$It comes free with a qualifying spend (not yet confirmed by LEGO) on a LEGO order while the promotion runs.$n0$), $o1$Corrected 29 Sep 2026: this article said there were no official details on 40900's release, theme or price, and estimated an import price of ₹2,700 from a US price of $19.99. LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately; the claim and the price are removed, and a stray second verdict line is deleted.$o1$, $n1$Corrected 29 Sep 2026: an earlier version included an unverified price estimate, which has been removed. It also said there were no official details on 40900's release, theme or price; LEGO had already revealed 40900 as a gift with purchase, which isn't sold separately, so that claim is removed too, and a stray second verdict line is deleted.$n1$)
  WHERE slug = 'lego-40900-scary-haunted-tree-is-this-weeks-surprise-hit' AND md5(content) = '24ea8e0361202d74da7cc666f86f1d73';
