-- boi:issue 471
-- boi:backup-tables public.news_articles, public.reviews, public.guides
-- boi:expect-before select (select count(*) from public.reviews where slug = 'lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag' and position('At an estimated import price of ₹23,300 — not confirmed India retail — you’ll be paying roughly 14 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-tribute-to-leonardo-da-vinci-40902-worth-19600' and position('At an estimated import price of ₹19,600 — not confirmed India retail — that''s about 13 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-vintage-steam-train-60511-worth-9999' and position('At ₹9,999 (estimated), that''s 10 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-fortnite-rave-cave-77082-worth-21999' and position('At ₹21,999 (estimated)' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999' and position('At ₹49,999 (estimated), that''s 14 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-heartlake-city-grand-hotel-42704-worth-15999-2' and position('At ₹15,999 (estimated), that''s 13 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-43014-scuderia-ferrari-hp-charles-leclerc-helmet-worth-' and position('At ₹9,999 (estimated)' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-tower-bridge-21067-worth-10300' and position('At an estimated import price of ₹10,300 — not confirmed India retail — that is about 8 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-gremlins-gizmo-and-stripe-40919-worth-3300' and position('The estimated import price for 40919 Gremlins: Gizmo and Stripe is ₹3,300.' in content) > 0) = 9
-- boi:expect-after select (select count(*) from public.reviews where slug = 'lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag' and position('At an estimated import price of ₹23,300 — not confirmed India retail — you’ll be paying roughly 14 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-tribute-to-leonardo-da-vinci-40902-worth-19600' and position('At an estimated import price of ₹19,600 — not confirmed India retail — that''s about 13 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-vintage-steam-train-60511-worth-9999' and position('At ₹9,999 (estimated), that''s 10 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-fortnite-rave-cave-77082-worth-21999' and position('At ₹21,999 (estimated)' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999' and position('At ₹49,999 (estimated), that''s 14 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-heartlake-city-grand-hotel-42704-worth-15999-2' and position('At ₹15,999 (estimated), that''s 13 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-43014-scuderia-ferrari-hp-charles-leclerc-helmet-worth-' and position('At ₹9,999 (estimated)' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-tower-bridge-21067-worth-10300' and position('At an estimated import price of ₹10,300 — not confirmed India retail — that is about 8 months of Netflix Premium.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-gremlins-gizmo-and-stripe-40919-worth-3300' and position('The estimated import price for 40919 Gremlins: Gizmo and Stripe is ₹3,300.' in content) > 0) = 0
-- Article text corrections approved by the owner (3 Oct 2026): 9 pages.
UPDATE public.reviews SET content = replace(content, 'At an estimated import price of ₹23,300 — not confirmed India retail — you’ll be paying roughly 14 months of Netflix Premium.', 'It’s a gift with purchase, so it has no Indian price of its own.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-40912-sea-serpent-gwp-2026-worth-the-23300-price-tag' AND position('At an estimated import price of ₹23,300 — not confirmed India retail — you’ll be paying roughly 14 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At an estimated import price of ₹19,600 — not confirmed India retail — that''s about 13 months of Netflix Premium.', 'It’s a gift with purchase, so it has no Indian price of its own.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-tribute-to-leonardo-da-vinci-40902-worth-19600' AND position('At an estimated import price of ₹19,600 — not confirmed India retail — that''s about 13 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At ₹9,999 (estimated), that''s 10 months of Netflix Premium.', 'At ₹9,999, that''s 10 months of Netflix Premium.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-vintage-steam-train-60511-worth-9999' AND position('At ₹9,999 (estimated), that''s 10 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At ₹21,999 (estimated)', 'At ₹21,999') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-fortnite-rave-cave-77082-worth-21999' AND position('At ₹21,999 (estimated)' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At ₹49,999 (estimated), that''s 14 months of Netflix Premium.', 'At ₹49,999, that''s 14 months of Netflix Premium.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-42232-koenigsegg-sadairs-spear-megacar-worth-49999' AND position('At ₹49,999 (estimated), that''s 14 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At ₹15,999 (estimated), that''s 13 months of Netflix Premium.', 'At ₹15,999, that''s 13 months of Netflix Premium.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-heartlake-city-grand-hotel-42704-worth-15999-2' AND position('At ₹15,999 (estimated), that''s 13 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At ₹9,999 (estimated)', 'At ₹9,999') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-43014-scuderia-ferrari-hp-charles-leclerc-helmet-worth-' AND position('At ₹9,999 (estimated)' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'At an estimated import price of ₹10,300 — not confirmed India retail — that is about 8 months of Netflix Premium.', 'It’s now sold in India; today’s price is shown on this page.') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-tower-bridge-21067-worth-10300' AND position('At an estimated import price of ₹10,300 — not confirmed India retail — that is about 8 months of Netflix Premium.' in content) > 0;
UPDATE public.reviews SET content = replace(replace(content, 'The estimated import price for 40919 Gremlins: Gizmo and Stripe is ₹3,300.', 'It’s now sold in India; today’s price is shown on this page.'), ' That''s enough for a substantial plate of dum biryani with all the trimmings, or a decent weekend getaway.', '') || '

*Correction (3 October 2026): we removed a US price, and any rupee figure worked out from it, because it isn''t the Indian price.*' WHERE slug = 'lego-gremlins-gizmo-and-stripe-40919-worth-3300' AND position('The estimated import price for 40919 Gremlins: Gizmo and Stripe is ₹3,300.' in content) > 0 AND position('That''s enough for a substantial plate of dum biryani with all the trimmings, or a decent weekend getaway.' in content) > 0;
