-- boi:issue 520
-- boi:backup-tables public.news_articles, public.reviews, public.guides
-- boi:expect-before select (select count(*) from public.news_articles where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) + (select count(*) from public.reviews where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) + (select count(*) from public.guides where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) = 633
-- boi:expect-after select (select count(*) from public.news_articles where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) + (select count(*) from public.reviews where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) + (select count(*) from public.guides where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0 or position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0 or position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0) = 0
-- Round 11 item 3 (B1/B2), chat's round 10 decision: the ABHINAV12 line in article text drops the commission
-- wording and says full-price. Round 3 (Abhinav, 2 Oct night): no disclosure beside the code (it lives on the legal
-- pages), so the new line is plain and matches AFFILIATE_NOTE (#527); gate 13 checks the exact clause. Only the
-- four standard wordings change (631 rows on 2 Oct ~13:40 UTC; recounted 4 Oct ~12:10 IST: 633 rows = 448 news, 179 reviews, 6 guides). The ~100
-- one-off FAQ/guide sentences are a separate, hand-edited fix. position() not LIKE: '12%' would be a wildcard.
-- If an article with an old line is published before this runs, the before-count is higher and nothing applies.
update public.news_articles set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0;
update public.news_articles set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.news_articles set content = replace(content, 'use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.news_articles set content = replace(content, 'Use code ABHINAV12 at Toycra for 12% off above ₹500.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0;
update public.reviews set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0;
update public.reviews set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.reviews set content = replace(content, 'use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.reviews set content = replace(content, 'Use code ABHINAV12 at Toycra for 12% off above ₹500.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0;
update public.guides set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra (we earn a commission).' in content) > 0;
update public.guides set content = replace(content, 'Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.guides set content = replace(content, 'use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.', 'code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('use code ABHINAV12 for 12% off on orders above ₹500 at Toycra.' in content) > 0;
update public.guides set content = replace(content, 'Use code ABHINAV12 at Toycra for 12% off above ₹500.', 'Code ABHINAV12 takes 12% off full-price sets at Toycra, minimum order ₹500.') where position('Use code ABHINAV12 at Toycra for 12% off above ₹500.' in content) > 0;
