-- boi:issue 540
-- boi:backup-tables public.reviews, public.news_articles
-- boi:expect-before select (select count(*) from public.reviews where slug = 'lego-creative-flower-shop-42693-worth-2999' and position('The review notes a missing leaf element, a minor manufacturing hiccup, but the overall impression is overwhelmingly positive.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-playstation-72306-worth-17000' and position('However, the review notes a significant number of stickers in this scene,' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-spongebob-squarepants-bikini-bottom-11386-worth-21000' and position('The build experience, according to the review, is pretty smooth.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-sagrada-famlia-21065-worth-76400' and position('The build experience, according to the review, is intricate,' in content) > 0) + (select count(*) from public.news_articles where slug = 'lego-buddy-the-elf-40865-festive-fun-or-festive-flop' and position('The reviewer notes that Buddy''s printed face looks better in person,' in content) > 0) = 5
-- boi:expect-after select (select count(*) from public.reviews where slug = 'lego-creative-flower-shop-42693-worth-2999' and position('The review notes a missing leaf element, a minor manufacturing hiccup, but the overall impression is overwhelmingly positive.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-playstation-72306-worth-17000' and position('However, the review notes a significant number of stickers in this scene,' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-spongebob-squarepants-bikini-bottom-11386-worth-21000' and position('The build experience, according to the review, is pretty smooth.' in content) > 0) + (select count(*) from public.reviews where slug = 'lego-sagrada-famlia-21065-worth-76400' and position('The build experience, according to the review, is intricate,' in content) > 0) + (select count(*) from public.news_articles where slug = 'lego-buddy-the-elf-40865-festive-fun-or-festive-flop' and position('The reviewer notes that Buddy''s printed face looks better in person,' in content) > 0) = 0
-- Round 11 (chat, 4 Oct 2026): 5 sentences now in our own words.
UPDATE public.reviews SET content = replace(content, 'The review notes a missing leaf element, a minor manufacturing hiccup, but the overall impression is overwhelmingly positive.', 'The overall impression is overwhelmingly positive.') WHERE slug = 'lego-creative-flower-shop-42693-worth-2999' AND position('The review notes a missing leaf element, a minor manufacturing hiccup, but the overall impression is overwhelmingly positive.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'However, the review notes a significant number of stickers in this scene,', 'However, there are a significant number of stickers in this scene,') WHERE slug = 'lego-playstation-72306-worth-17000' AND position('However, the review notes a significant number of stickers in this scene,' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'The build experience, according to the review, is pretty smooth.', 'The build is pretty smooth.') WHERE slug = 'lego-spongebob-squarepants-bikini-bottom-11386-worth-21000' AND position('The build experience, according to the review, is pretty smooth.' in content) > 0;
UPDATE public.reviews SET content = replace(content, 'The build experience, according to the review, is intricate,', 'The build is intricate,') WHERE slug = 'lego-sagrada-famlia-21065-worth-76400' AND position('The build experience, according to the review, is intricate,' in content) > 0;
UPDATE public.news_articles SET content = replace(content, 'The reviewer notes that Buddy''s printed face looks better in person,', 'Buddy''s printed face looks better in person,') WHERE slug = 'lego-buddy-the-elf-40865-festive-fun-or-festive-flop' AND position('The reviewer notes that Buddy''s printed face looks better in person,' in content) > 0;
